var window=global;var $CLJS=require("./cljs_env");require("./goog.base.js");require("./cljs.core.js");require("./clojure.walk.js");require("./goog.array.array.js");require("./goog.string.internal.js");require("./clojure.string.js");
var zh,Ih,Sh,$h,ai,bi,di,fi,ii,ji,ki,ui,Fi,Pi,Vi,bj,dj,ij,nj,yj,Bj,Ej,Xi,aj,Ni,lj,rj,ej,ei,xj,ci,Nk,Rk,Yk,qj,pl,ql,wj,tl,mj,Mi,Hj,Lj,Ri,Li,mk,vk,uj,Mk,si,Yi,il,Wi,kl,sj,sl,$i,oj;zh=function(){};$CLJS.Dh=function(a){return $CLJS.Ch(a)?a:(a=$CLJS.F(a))?a:$CLJS.Qb};Ih=function(a){this.ob=a;this.v=null;this.g=2153775104;this.w=2048};
$CLJS.Jh=function(){function a(){return Math.floor(16*Math.random()).toString(16)}var b=(8|3&Math.floor(16*Math.random())).toString(16);return new Ih([$CLJS.z.a(a()),$CLJS.z.a(a()),$CLJS.z.a(a()),$CLJS.z.a(a()),$CLJS.z.a(a()),$CLJS.z.a(a()),$CLJS.z.a(a()),$CLJS.z.a(a()),"-",$CLJS.z.a(a()),$CLJS.z.a(a()),$CLJS.z.a(a()),$CLJS.z.a(a()),"-4",$CLJS.z.a(a()),$CLJS.z.a(a()),$CLJS.z.a(a()),"-",$CLJS.z.a(b),$CLJS.z.a(a()),$CLJS.z.a(a()),$CLJS.z.a(a()),"-",$CLJS.z.a(a()),$CLJS.z.a(a()),$CLJS.z.a(a()),$CLJS.z.a(a()),
$CLJS.z.a(a()),$CLJS.z.a(a()),$CLJS.z.a(a()),$CLJS.z.a(a()),$CLJS.z.a(a()),$CLJS.z.a(a()),$CLJS.z.a(a()),$CLJS.z.a(a())].join("").toLowerCase())};
Sh=function(){return function(){function a(g,k,l){return new $CLJS.R(null,2,5,$CLJS.T,[$CLJS.Rh.f?$CLJS.Rh.f(g,k,l):$CLJS.Rh(g,k,l),$CLJS.Qh.f?$CLJS.Qh.f(g,k,l):$CLJS.Qh(g,k,l)],null)}function b(g,k){return new $CLJS.R(null,2,5,$CLJS.T,[$CLJS.Rh.b?$CLJS.Rh.b(g,k):$CLJS.Rh(g,k),$CLJS.Qh.b?$CLJS.Qh.b(g,k):$CLJS.Qh(g,k)],null)}function c(g){return new $CLJS.R(null,2,5,$CLJS.T,[$CLJS.Rh.a?$CLJS.Rh.a(g):$CLJS.Rh(g),$CLJS.Qh.a?$CLJS.Qh.a(g):$CLJS.Qh(g)],null)}function d(){return new $CLJS.R(null,2,5,$CLJS.T,
[$CLJS.Rh.u?$CLJS.Rh.u():$CLJS.Rh(),$CLJS.Qh.u?$CLJS.Qh.u():$CLJS.Qh()],null)}var e=null,f=function(){function g(l,m,n,p){var v=null;if(3<arguments.length){v=0;for(var u=Array(arguments.length-3);v<u.length;)u[v]=arguments[v+3],++v;v=new $CLJS.Nb(u,0,null)}return k.call(this,l,m,n,v)}function k(l,m,n,p){return new $CLJS.R(null,2,5,$CLJS.T,[$CLJS.Jd($CLJS.Rh,l,m,n,p),$CLJS.Jd($CLJS.Qh,l,m,n,p)],null)}g.A=3;g.C=function(l){var m=$CLJS.H(l);l=$CLJS.K(l);var n=$CLJS.H(l);l=$CLJS.K(l);var p=$CLJS.H(l);
l=$CLJS.Rb(l);return k(m,n,p,l)};g.j=k;return g}();e=function(g,k,l,m){switch(arguments.length){case 0:return d.call(this);case 1:return c.call(this,g);case 2:return b.call(this,g,k);case 3:return a.call(this,g,k,l);default:var n=null;if(3<arguments.length){n=0;for(var p=Array(arguments.length-3);n<p.length;)p[n]=arguments[n+3],++n;n=new $CLJS.Nb(p,0,null)}return f.j(g,k,l,n)}throw Error("Invalid arity: "+arguments.length);};e.A=3;e.C=f.C;e.u=d;e.a=c;e.b=b;e.f=a;e.j=f.j;return e}()};
$h=function(a){if($CLJS.nd(a)){var b=$CLJS.Zb($CLJS.Zh);a=$CLJS.N.b(b,a);if($CLJS.nd(a))a:for(;;)if($CLJS.nd(a))a=$CLJS.N.b(b,a);else{b=a;break a}else b=a;return b}return a};ai=function(a){if($CLJS.nd(a)){var b=$h(a);if($CLJS.q(b))return b;throw Error(["Unable to resolve spec: ",$CLJS.z.a(a)].join(""));}return a};bi=function(a){return null!=a&&$CLJS.Gb===a.vb?a:null};di=function(a){var b=ci.a(a);return $CLJS.q(b)?a:b};
fi=function(a,b){return $CLJS.nd(a)?a:$CLJS.q(di(a))?$CLJS.kg.f(a,ei,b):null!=a&&(a.g&131072||$CLJS.Gb===a.fc)?$CLJS.xc(a,$CLJS.kg.f($CLJS.zc(a),ei,b)):null};$CLJS.gi=function(a){return $CLJS.nd(a)?a:$CLJS.q(di(a))?ei.a(a):null!=a&&(a.g&131072||$CLJS.Gb===a.fc)?ei.a($CLJS.zc(a)):null};ii=function(a){var b=function(){var c=(c=$CLJS.nd(a))?$h(a):c;if($CLJS.q(c))return c;c=bi(a);if($CLJS.q(c))return c;c=di(a);return $CLJS.q(c)?c:null}();return $CLJS.q(di(b))?fi(hi(b,null),$CLJS.gi(b)):b};
ji=function(a){var b=ii(a);if($CLJS.q(b))return b;if($CLJS.nd(a))throw Error(["Unable to resolve spec: ",$CLJS.z.a(a)].join(""));return null};ki=function(a){if($CLJS.Lq(a))return null;var b=$CLJS.he.b($CLJS.Ph,$CLJS.Wq(a,"$"));if(2<=$CLJS.ic(b)&&$CLJS.Ud(function(){return function(d){return!$CLJS.Lq(d)}}(b),b)){var c=function(){var d=Sh();return d.a?d.a(b):d(b)}();a=$CLJS.uc(c,0,null);c=$CLJS.uc(c,1,null);return $CLJS.ch.a([$CLJS.z.a($CLJS.Hh(".",a)),"/",$CLJS.z.a(c)].join(""))}return null};
$CLJS.mi=function(a){return $CLJS.kd($CLJS.li,a)};$CLJS.ri=function(a,b){return $CLJS.ni($CLJS.oi.a(a),b)};ui=function(a,b){a=$h(a);return $CLJS.q(di(a))?$CLJS.kg.f(a,si,b):ti($CLJS.oi.a(a),b)};$CLJS.xi=function(a,b,c){if(null==c)$CLJS.xg.f($CLJS.Zh,$CLJS.vi,a);else{var d=bi(c);$CLJS.q(d)||(d=di(c),d=$CLJS.q(d)?d:$CLJS.N.b($CLJS.Zb($CLJS.Zh),c));b=$CLJS.q(d)?c:$CLJS.wi(b,c,null);$CLJS.xg.s($CLJS.Zh,$CLJS.kg,a,fi(b,a))}};
$CLJS.yi=function(a,b,c,d){if($CLJS.q(a)){var e=ji(a);if($CLJS.q(e))return $CLJS.ri(e,b);if($CLJS.Bh(a)||(null!=a?a.g&1||$CLJS.Gb===a.Dd||(a.g?0:$CLJS.Za(zh,a)):$CLJS.Za(zh,a)))return $CLJS.q(d)?a.a?a.a(b):a(b):$CLJS.q(a.a?a.a(b):a(b))?b:$CLJS.li;throw Error([$CLJS.Xq.j($CLJS.pc([c]))," is not a fn, expected predicate fn"].join(""));}return b};
$CLJS.Ei=function(a,b,c,d,e,f){b=ii(b);$CLJS.q(bi(b))?(a=$CLJS.gi(b),d=$CLJS.q(a)?$CLJS.fh.b(d,a):d,c=$CLJS.zi(b,c,d,e,f)):c=new $CLJS.R(null,1,5,$CLJS.T,[new $CLJS.Ka(null,5,[$CLJS.Ai,c,$CLJS.Bi,a,$CLJS.Hg,f,$CLJS.Ci,d,$CLJS.Di,e],null)],null);return c};$CLJS.wi=function(a,b,c){return Fi(a,b,null,c,null)};
Fi=function(a,b,c,d,e){if($CLJS.q(bi(b)))return $CLJS.q(c)?ui(b,c):b;if($CLJS.q(di(b)))return hi(b,c);if($CLJS.nd(b))return a=ji(b),$CLJS.q(c)?ui(a,c):a;if("undefined"===typeof $CLJS.Nd||"undefined"===typeof $CLJS.Gi||"undefined"===typeof $CLJS.Hi||"undefined"===typeof Ii)Ii=function(f,g,k,l,m,n){this.form=f;this.Ra=g;this.Ha=k;this.Vb=l;this.Ac=m;this.gd=n;this.g=393216;this.w=0},Ii.prototype.K=function(f,g){return new Ii(this.form,this.Ra,this.Ha,this.Vb,this.Ac,g)},Ii.prototype.J=function(){return this.gd},
Ii.prototype.Pa=function(){return this},Ii.prototype.Qa=function(){return this},Ii.prototype.vb=$CLJS.Gb,Ii.prototype.ib=function(f,g){f=this.Ra.a?this.Ra.a(g):this.Ra(g);return $CLJS.q(this.Vb)?f:$CLJS.q(f)?g:$CLJS.li},Ii.prototype.jb=function(f,g,k,l,m){return $CLJS.mi($CLJS.yi(this.Ra,m,this.form,this.Vb))?new $CLJS.R(null,1,5,$CLJS.T,[new $CLJS.Ka(null,5,[$CLJS.Ai,g,$CLJS.Bi,this.form,$CLJS.Hg,m,$CLJS.Ci,k,$CLJS.Di,l],null)],null):null},Ii.prototype.kb=function(f,g){return Fi(this.form,this.Ra,
g,this.Vb,this.Ac)},Ii.yb=function(){return new $CLJS.R(null,6,5,$CLJS.T,[$CLJS.Kg,$CLJS.Ji,$CLJS.Ki,Li,Mi,Ni],null)},Ii.ab=!0,Ii.Oa="cljs.spec.alpha/t_cljs$spec$alpha8301",Ii.hb=function(f,g){return $CLJS.Rd(g,"cljs.spec.alpha/t_cljs$spec$alpha8301")};return new Ii(a,b,c,d,e,$CLJS.Sd)};$CLJS.Oi=function(a,b){return new $CLJS.Xe(a,b)};
Pi=function(a,b,c){var d=$CLJS.F(b);$CLJS.H(d);$CLJS.K(d);d=$CLJS.F(c);$CLJS.H(d);$CLJS.K(d);for(d=c;;){c=a;b=$CLJS.F(b);a=$CLJS.H(b);b=$CLJS.K(b);var e=$CLJS.F(d);d=$CLJS.H(e);e=$CLJS.K(e);var f=d;d=e;if($CLJS.q(a)){c=$CLJS.yi(a,c,f,null);if($CLJS.mi(c))return $CLJS.li;a=c}else return c}};
$CLJS.Qi=function(a,b,c,d,e,f){var g=$CLJS.F(a);$CLJS.H(g);$CLJS.K(g);g=$CLJS.F(b);$CLJS.H(g);$CLJS.K(g);for(g=b;;){b=f;a=$CLJS.F(a);f=$CLJS.H(a);a=$CLJS.K(a);var k=$CLJS.F(g);g=$CLJS.H(k);var l=$CLJS.K(k);k=g;if($CLJS.q(k)){g=$CLJS.yi(k,b,f,null);if($CLJS.mi(g))return $CLJS.Ei(f,k,c,d,e,b);b=a;k=l;f=g;a=b;g=k}else return null}};$CLJS.Ti=function(a){return new $CLJS.Ka(null,2,[ci,Ri,$CLJS.Si,a],null)};
Vi=function(a){a=null!=a&&(a.g&64||$CLJS.Gb===a.T)?$CLJS.Gd($CLJS.Ui,a):a;a=$CLJS.N.b(a,ci);return $CLJS.M.b(Ri,a)};bj=function(a,b,c,d,e){return $CLJS.q(a)?(d=new $CLJS.Ka(null,5,[ci,Wi,Xi,b,Yi,d,$CLJS.Zi,e,$i,$CLJS.Jh()],null),Vi(a)?$CLJS.kg.j(d,aj,b,$CLJS.pc([$CLJS.Si,$CLJS.fh.b(c,$CLJS.Si.a(a))])):$CLJS.kg.j(d,aj,a,$CLJS.pc([$CLJS.Si,c]))):null};
dj=function(a,b,c,d){return $CLJS.q($CLJS.q(b)?b:c)?(a=$CLJS.je(function(e){e=$CLJS.H(e);return d.a?d.a(e):d(e)},$CLJS.he.s($CLJS.cj,a,function(){var e=$CLJS.F(b);return e?e:$CLJS.de(null)}(),function(){var e=$CLJS.F(c);return e?e:$CLJS.de(null)}())),new $CLJS.R(null,3,5,$CLJS.T,[$CLJS.F($CLJS.he.b($CLJS.H,a)),$CLJS.q(b)?$CLJS.F($CLJS.he.b($CLJS.rc,a)):null,$CLJS.q(c)?$CLJS.F($CLJS.he.b(function(){return function(e){return $CLJS.kc(e,2)}}(a),a)):null],null)):new $CLJS.R(null,3,5,$CLJS.T,[$CLJS.F($CLJS.je(d,
a)),b,c],null)};$CLJS.hj=function(a,b,c){var d=dj(a,b,c,$CLJS.$c);b=$CLJS.uc(d,0,null);c=$CLJS.F(b);a=$CLJS.H(c);c=$CLJS.K(c);var e=$CLJS.uc(d,1,null),f=$CLJS.uc(e,0,null);d=$CLJS.uc(d,2,null);return $CLJS.q(b)?(b=new $CLJS.Ka(null,4,[ci,ej,$CLJS.fj,b,$CLJS.gj,e,$CLJS.Zi,d],null),null==c?$CLJS.q(f)?Vi(a)?$CLJS.Ti($CLJS.Oi(f,$CLJS.Si.a(a))):b:a:b):null};ij=function(a,b){return $CLJS.q($CLJS.q(a)?b:a)?$CLJS.hj($CLJS.pc([a,b]),null,null):$CLJS.q(a)?a:b};
nj=function(a,b,c){var d=ai(a);a=null!=d&&(d.g&64||$CLJS.Gb===d.T)?$CLJS.Gd($CLJS.Ui,d):d;var e=$CLJS.N.b(a,ci),f=$CLJS.N.b(a,$CLJS.fj),g=$CLJS.N.b(a,Yi);d=function(k,l,m,n,p,v){return function(){var u=jj(m);if($CLJS.Ac(u))return b;u=$CLJS.q(c)?$CLJS.$e([c,u]):u;var x=$CLJS.q(v)?$CLJS.gh:$CLJS.fh;return x.b?x.b(b,u):x(b,u)}}(d,a,a,e,f,g);if($CLJS.M.b(null,e))return b;if($CLJS.M.b(ej,e)||$CLJS.M.b(Ri,e)||$CLJS.M.b(lj,e))return a=jj(a),$CLJS.M.b(a,$CLJS.kj)?b:$CLJS.fh.b(b,$CLJS.q(c)?$CLJS.$e([c,a]):
a);if($CLJS.M.b(Wi,e)||$CLJS.M.b(mj,e))return d();throw Error(["No matching clause: ",$CLJS.z.a(e)].join(""));};
yj=function(a){a=ai(a);var b=null!=a&&(a.g&64||$CLJS.Gb===a.T)?$CLJS.Gd($CLJS.Ui,a):a;$CLJS.N.b(b,$CLJS.fj);a=$CLJS.N.b(b,$CLJS.Zi);var c=$CLJS.N.b(b,oj),d=$CLJS.N.b(b,ci),e=$CLJS.N.b(b,Yi),f=$CLJS.N.b(b,$CLJS.gj),g=$CLJS.N.b(b,$CLJS.pj),k=$CLJS.N.b(b,qj);$CLJS.N.b(b,aj);if($CLJS.q(b)){if($CLJS.M.b(Ri,d))return null;if($CLJS.M.b(null,d))return b;if($CLJS.M.b(lj,d))return $CLJS.jd(rj,$CLJS.jd(k,a));if($CLJS.M.b(mj,d))return $CLJS.q(c)?a=new $CLJS.fd(null,sj,new $CLJS.fd(null,c,null,1,null),2,null):
(b=$CLJS.F(f),a=$CLJS.jd($CLJS.tj,$CLJS.ie($CLJS.cj,$CLJS.pc([b?b:$CLJS.de(uj),a])))),a;if($CLJS.M.b(ej,d))return $CLJS.q(g)?new $CLJS.fd(null,$CLJS.vj,new $CLJS.fd(null,g,null,1,null),2,null):$CLJS.jd(wj,$CLJS.ie($CLJS.cj,$CLJS.pc([f,a])));if($CLJS.M.b(Wi,d))return new $CLJS.fd(null,$CLJS.q(e)?sj:xj,new $CLJS.fd(null,a,null,1,null),2,null);throw Error(["No matching clause: ",$CLJS.z.a(d)].join(""));}return null};
Bj=function(a,b){for(;;){var c=$CLJS.F(b),d=$CLJS.H(c);c=$CLJS.K(c);if($CLJS.Ac(b))return $CLJS.q(zj(a))?(a=jj(a),$CLJS.M.b(a,$CLJS.kj)?null:a):$CLJS.li;a=Aj(a,d);if($CLJS.q(a))b=c;else return $CLJS.li}};$CLJS.Gi={};$CLJS.h=Ih.prototype;$CLJS.h.toString=function(){return this.ob};$CLJS.h.R=function(a,b){return b instanceof Ih&&this.ob===b.ob};$CLJS.h.P=function(a,b){return $CLJS.Rd(b,['#uuid "',$CLJS.z.a(this.ob),'"'].join(""))};$CLJS.h.U=function(){null==this.v&&(this.v=$CLJS.Ib(this.ob));return this.v};
$CLJS.h.Fa=function(a,b){return $CLJS.Ia(this.ob,b.ob)};Ej=new $CLJS.C(null,"p1__8978#","p1__8978#",-1570496039,null);$CLJS.Fj=new $CLJS.C(null,"argm","argm",-181546357,null);Xi=new $CLJS.Q(null,"p2","p2",905500641);aj=new $CLJS.Q(null,"p1","p1",-936759954);Ni=new $CLJS.C(null,"meta8302","meta8302",745628697,null);$CLJS.Nj=new $CLJS.C(null,"meta8513","meta8513",-675803726,null);$CLJS.Qj=new $CLJS.C("cljs.core","coll?","cljs.core/coll?",1208130522,null);
$CLJS.Rj=new $CLJS.C(null,"keys-\x3especnames","keys-\x3especnames",1791294693,null);$CLJS.Sj=new $CLJS.C(null,"conform-keys","conform-keys",-159510287,null);$CLJS.gj=new $CLJS.Q(null,"ks","ks",1900203942);lj=new $CLJS.Q("cljs.spec.alpha","amp","cljs.spec.alpha/amp",831147508);rj=new $CLJS.C("cljs.spec.alpha","\x26","cljs.spec.alpha/\x26",1635809823,null);ej=new $CLJS.Q("cljs.spec.alpha","alt","cljs.spec.alpha/alt",523685437);$CLJS.Wj=new $CLJS.C("cljs.core","fn","cljs.core/fn",-1065745098,null);
$CLJS.Xj=new $CLJS.C(null,"opt-un","opt-un",-1770993273,null);$CLJS.kj=new $CLJS.Q("cljs.spec.alpha","nil","cljs.spec.alpha/nil",1733813950);$CLJS.Yj=new $CLJS.Q("cljs.spec.alpha","kind-form","cljs.spec.alpha/kind-form",-1047104697);$CLJS.Zj=new $CLJS.C(null,"conform-into","conform-into",-1039113729,null);$CLJS.ck=new $CLJS.C(null,"p__8244","p__8244",-671160158,null);$CLJS.fj=new $CLJS.Q(null,"ps","ps",292358046);$CLJS.gk=new $CLJS.C(null,"max-count","max-count",-1115250464,null);
$CLJS.hk=new $CLJS.Q(null,"conform-keys","conform-keys",-1800041814);$CLJS.jk=new $CLJS.C(null,"p__8495","p__8495",-1918566777,null);$CLJS.nk=new $CLJS.C(null,"forms","forms",-608443419,null);$CLJS.ok=new $CLJS.Q(null,"opt-un","opt-un",883442496);$CLJS.tj=new $CLJS.C("cljs.spec.alpha","cat","cljs.spec.alpha/cat",-1471398329,null);$CLJS.Ji=new $CLJS.C(null,"pred","pred",-727012372,null);$CLJS.xk=new $CLJS.C(null,"kfn","kfn",729311001,null);$CLJS.yk=new $CLJS.C(null,"cform","cform",1319506748,null);
$CLJS.zk=new $CLJS.C(null,"kind-form","kind-form",1155997457,null);$CLJS.Bk=new $CLJS.C("cljs.core","or","cljs.core/or",1201033885,null);ei=new $CLJS.Q("cljs.spec.alpha","name","cljs.spec.alpha/name",205233570);$CLJS.Ck=new $CLJS.C(null,"opt","opt",845825158,null);$CLJS.Ek=new $CLJS.C(null,"distinct?","distinct?",-1684357959,null);xj=new $CLJS.C("cljs.spec.alpha","*","cljs.spec.alpha/*",-1238084288,null);$CLJS.Kk=new $CLJS.C(null,"k-\x3es","k-\x3es",-1685112801,null);
ci=new $CLJS.Q("cljs.spec.alpha","op","cljs.spec.alpha/op",-1269055252);Nk=new $CLJS.C(null,"k","k",-505765866,null);$CLJS.Ok=new $CLJS.C(null,"opt-specs","opt-specs",1255626077,null);$CLJS.Pk=new $CLJS.C(null,"map__8496","map__8496",453296812,null);$CLJS.Qk=new $CLJS.C(null,"cpred","cpred",-540353554,null);Rk=new $CLJS.C(null,"re","re",1869207729,null);$CLJS.Sk=new $CLJS.Q("cljs.spec.alpha","problems","cljs.spec.alpha/problems",447400814);
$CLJS.Tk=new $CLJS.C(null,"map__8248","map__8248",1731672618,null);$CLJS.Uk=new $CLJS.Q("cljs.spec.alpha","spec","cljs.spec.alpha/spec",1947137578);$CLJS.Vk=new $CLJS.Q(null,"gen-max","gen-max",-793680445);$CLJS.Wk=new $CLJS.C(null,"addcv","addcv",-1552991247,null);Yk=new $CLJS.C("cljs.core","set?","cljs.core/set?",-1176684971,null);$CLJS.Zk=new $CLJS.C("cljs.spec.alpha","or","cljs.spec.alpha/or",-831679639,null);$CLJS.al=new $CLJS.C(null,"min-count","min-count",-1059726756,null);
$CLJS.cl=new $CLJS.Q(null,"into","into",-150836029);$CLJS.el=new $CLJS.C("cljs.core","map?","cljs.core/map?",-1390345523,null);qj=new $CLJS.Q(null,"amp","amp",271690571);$CLJS.fl=new $CLJS.C(null,"preds","preds",150921777,null);$CLJS.hl=new $CLJS.Q("cljs.spec.alpha","cpred","cljs.spec.alpha/cpred",-693471218);$CLJS.pj=new $CLJS.Q(null,"maybe","maybe",-314397560);$CLJS.ml=new $CLJS.Q(null,"req-un","req-un",1074571008);$CLJS.Zi=new $CLJS.Q(null,"forms","forms",2045992350);
$CLJS.nl=new $CLJS.C("cljs.spec.alpha","and","cljs.spec.alpha/and",-2060279705,null);pl=new $CLJS.Q("cljs.spec.alpha","v","cljs.spec.alpha/v",552625740);ql=new $CLJS.Q("cljs.spec.alpha","k","cljs.spec.alpha/k",-1602615178);wj=new $CLJS.C("cljs.spec.alpha","alt","cljs.spec.alpha/alt",-2130750332,null);tl=new $CLJS.C("cljs.core","sequential?","cljs.core/sequential?",1777854658,null);$CLJS.ul=new $CLJS.C(null,"%","%",-950237169,null);
$CLJS.li=new $CLJS.Q("cljs.spec.alpha","invalid","cljs.spec.alpha/invalid",-1220295119);mj=new $CLJS.Q("cljs.spec.alpha","pcat","cljs.spec.alpha/pcat",26406623);Mi=new $CLJS.C(null,"unc","unc",-465250751,null);$CLJS.Al=new $CLJS.C(null,"kind","kind",923265724,null);$CLJS.Bl=new $CLJS.Q(null,"distinct","distinct",-1788879121);$CLJS.El=new $CLJS.C("cljs.core","count","cljs.core/count",-921270233,null);$CLJS.Gj=new $CLJS.C("cljs.core","\x3c\x3d","cljs.core/\x3c\x3d",1677001748,null);
Hj=new $CLJS.C("cljs.core","zipmap","cljs.core/zipmap",-1902130674,null);$CLJS.Ij=new $CLJS.Q(null,"pred-forms","pred-forms",172611832);$CLJS.Jj=new $CLJS.C(null,"meta8419","meta8419",1645210456,null);$CLJS.Kj=new $CLJS.C(null,"describe-form","describe-form",-1410156588,null);Lj=new $CLJS.Q("cljs.spec.alpha","kvs-\x3emap","cljs.spec.alpha/kvs-\x3emap",579713455);$CLJS.Mj=new $CLJS.Q(null,"kind","kind",-717265803);$CLJS.Tj=new $CLJS.C(null,"opt-keys","opt-keys",-1391747508,null);
$CLJS.Uj=new $CLJS.Q(null,"gfn","gfn",791517474);$CLJS.Vj=new $CLJS.C(null,"check?","check?",409539557,null);Ri=new $CLJS.Q("cljs.spec.alpha","accept","cljs.spec.alpha/accept",370988198);$CLJS.ak=new $CLJS.Q(null,"keys-pred","keys-pred",858984739);$CLJS.bk=new $CLJS.C(null,"meta8469","meta8469",-2076283514,null);Li=new $CLJS.C(null,"cpred?","cpred?",35589515,null);$CLJS.dk=new $CLJS.C("cljs.spec.alpha","keys","cljs.spec.alpha/keys",1109346032,null);$CLJS.Ai=new $CLJS.Q(null,"path","path",-188191168);
$CLJS.ek=new $CLJS.C(null,"req-un","req-un",-1579864761,null);$CLJS.fk=new $CLJS.C(null,"req-specs","req-specs",-2100473456,null);$CLJS.ik=new $CLJS.C(null,"specs","specs",-1227865028,null);$CLJS.kk=new $CLJS.C(null,"req-keys","req-keys",-2140116548,null);$CLJS.lk=new $CLJS.C(null,"meta8251","meta8251",1386948632,null);mk=new $CLJS.C(null,"p1__8979#","p1__8979#",-518190252,null);$CLJS.Ci=new $CLJS.Q(null,"via","via",-1904457336);$CLJS.pk=new $CLJS.Q(null,"opt-specs","opt-specs",-384905450);
$CLJS.qk=new $CLJS.Q(null,"pred-exprs","pred-exprs",1792271395);$CLJS.rk=new $CLJS.C(null,"id","id",252129435,null);$CLJS.sk=new $CLJS.Q("cljs.spec.alpha","kfn","cljs.spec.alpha/kfn",672643897);$CLJS.tk=new $CLJS.C(null,"conform-all","conform-all",-980179459,null);$CLJS.uk=new $CLJS.Q(null,"min-count","min-count",1594709013);vk=new $CLJS.C("cljs.core","vector?","cljs.core/vector?",-1550392028,null);$CLJS.wk=new $CLJS.C(null,"gen-into","gen-into",592640985,null);
$CLJS.Ak=new $CLJS.Q("cljs.spec.alpha","value","cljs.spec.alpha/value",1974786274);uj=new $CLJS.Q(null,"_","_",1453416199);$CLJS.Dk=new $CLJS.Q(null,"req","req",-326448303);$CLJS.Si=new $CLJS.Q(null,"ret","ret",-468222814);$CLJS.Fk=new $CLJS.C(null,"keys-pred","keys-pred",-1795451030,null);$CLJS.Gk=new $CLJS.C(null,"cfns","cfns",1335482066,null);$CLJS.Hk=new $CLJS.C(null,"gen-max","gen-max",846851082,null);$CLJS.Ik=new $CLJS.Q(null,"req-specs","req-specs",553962313);
$CLJS.Jk=new $CLJS.C(null,"distinct","distinct",-148347594,null);$CLJS.Lk=new $CLJS.C("cljs.spec.alpha","conformer","cljs.spec.alpha/conformer",2140085535,null);Mk=new $CLJS.C("cljs.core","list?","cljs.core/list?",-684796618,null);si=new $CLJS.Q("cljs.spec.alpha","gfn","cljs.spec.alpha/gfn",-593120375);$CLJS.Ki=new $CLJS.C(null,"gfn","gfn",-1862918295,null);$CLJS.Xk=new $CLJS.C("cljs.core","\x3d","cljs.core/\x3d",-1891498332,null);$CLJS.bl=new $CLJS.C(null,"kps","kps",-1157342767,null);
Yi=new $CLJS.Q(null,"splice","splice",449588165);$CLJS.dl=new $CLJS.Q("cljs.spec.alpha","describe","cljs.spec.alpha/describe",1883026911);$CLJS.gl=new $CLJS.C(null,"pred-forms","pred-forms",1813143359,null);$CLJS.Bi=new $CLJS.Q(null,"pred","pred",1927423397);il=new $CLJS.C("cljs.core","map","cljs.core/map",-338988913,null);Wi=new $CLJS.Q("cljs.spec.alpha","rep","cljs.spec.alpha/rep",1483217317);$CLJS.jl=new $CLJS.Q(null,"args","args",1315556576);
kl=new $CLJS.C(null,"meta8923","meta8923",-1841821934,null);$CLJS.ll=new $CLJS.Q(null,"opt-keys","opt-keys",1262688261);$CLJS.ol=new $CLJS.C(null,"opts","opts",1795607228,null);sj=new $CLJS.C("cljs.spec.alpha","+","cljs.spec.alpha/+",2101263265,null);$CLJS.rl=new $CLJS.Q(null,"req-keys","req-keys",514319221);sl=new $CLJS.C("cljs.core","nil?","cljs.core/nil?",945071861,null);$CLJS.vj=new $CLJS.C("cljs.spec.alpha","?","cljs.spec.alpha/?",1605136319,null);
$CLJS.vl=new $CLJS.C(null,"req","req",1314083224,null);$CLJS.Di=new $CLJS.Q(null,"in","in",-1531184865);$CLJS.wl=new $CLJS.Q("cljs.spec.alpha","unknown","cljs.spec.alpha/unknown",651034818);$CLJS.xl=new $CLJS.Q(null,"opt","opt",-794706369);$i=new $CLJS.Q(null,"id","id",-1388402092);oj=new $CLJS.Q(null,"rep+","rep+",-281382396);$CLJS.zl=new $CLJS.C(null,"pred-exprs","pred-exprs",-862164374,null);$CLJS.Cl=new $CLJS.C(null,"spec","spec",1988051928,null);
$CLJS.Dl=new $CLJS.Q("cljs.spec.alpha","conform-all","cljs.spec.alpha/conform-all",45201917);$CLJS.Fl=new $CLJS.Q(null,"max-count","max-count",1539185305);var Ii,Gl,ti,zj,jj,Aj,Kl,hi;$CLJS.Hi={};$CLJS.ni=function ni(a,b){if(null!=a&&null!=a.ib)return a.ib(a,b);var d=ni[$CLJS.Ca(null==a?null:a)];if(null!=d)return d.b?d.b(a,b):d(a,b);d=ni._;if(null!=d)return d.b?d.b(a,b):d(a,b);throw $CLJS.ab("Spec.conform*",a);};
$CLJS.zi=function zi(a,b,c,d,e){if(null!=a&&null!=a.jb)return a.jb(a,b,c,d,e);var g=zi[$CLJS.Ca(null==a?null:a)];if(null!=g)return g.I?g.I(a,b,c,d,e):g(a,b,c,d,e);g=zi._;if(null!=g)return g.I?g.I(a,b,c,d,e):g(a,b,c,d,e);throw $CLJS.ab("Spec.explain*",a);};ti=function ti(a,b){if(null!=a&&null!=a.kb)return a.kb(a,b);var d=ti[$CLJS.Ca(null==a?null:a)];if(null!=d)return d.b?d.b(a,b):d(a,b);d=ti._;if(null!=d)return d.b?d.b(a,b):d(a,b);throw $CLJS.ab("Spec.with-gen*",a);};
if("undefined"===typeof $CLJS.Nd||"undefined"===typeof $CLJS.Gi||"undefined"===typeof $CLJS.Hi||"undefined"===typeof $CLJS.Zh)$CLJS.Zh=$CLJS.Wd($CLJS.Sd);var Hl=function Hl(a){switch(arguments.length){case 1:return Hl.a(arguments[0]);case 2:return Hl.b(arguments[0],arguments[1]);default:throw Error(["Invalid arity: ",$CLJS.z.a(arguments.length)].join(""));}};
Hl.a=function(a){if(null!=a&&null!=a.Pa)return a.Pa(a);var b=Hl[$CLJS.Ca(null==a?null:a)];if(null!=b)return b.a?b.a(a):b(a);b=Hl._;if(null!=b)return b.a?b.a(a):b(a);throw $CLJS.ab("Specize.specize*",a);};Hl.b=function(a,b){if(null!=a&&null!=a.Qa)return a.Qa(a,b);var c=Hl[$CLJS.Ca(null==a?null:a)];if(null!=c)return c.b?c.b(a,b):c(a,b);c=Hl._;if(null!=c)return c.b?c.b(a,b):c(a,b);throw $CLJS.ab("Specize.specize*",a);};Hl.A=2;$CLJS.Q.prototype.Pa=function(){return Hl.a(ai(this))};
$CLJS.Q.prototype.Qa=function(){return Hl.a(ai(this))};$CLJS.C.prototype.Pa=function(){return Hl.a(ai(this))};$CLJS.C.prototype.Qa=function(){return Hl.a(ai(this))};$CLJS.Pf.prototype.Pa=function(){return $CLJS.wi(this,this,null)};$CLJS.Pf.prototype.Qa=function(a,b){return $CLJS.wi(b,this,null)};
Hl._=function(){function a(d,e){return $CLJS.wi(e,d,null)}function b(d){var e=(e=$CLJS.Bh(d))?ki(d.name):e;return $CLJS.q(e)?$CLJS.wi(e,d,null):$CLJS.wi($CLJS.wl,d,null)}var c=null;c=function(d,e){switch(arguments.length){case 1:return b.call(this,d);case 2:return a.call(this,d,e)}throw Error("Invalid arity: "+arguments.length);};c.a=b;c.b=a;return c}();
$CLJS.oi=function oi(a){switch(arguments.length){case 1:return oi.a(arguments[0]);case 2:return oi.b(arguments[0],arguments[1]);default:throw Error(["Invalid arity: ",$CLJS.z.a(arguments.length)].join(""));}};$CLJS.oi.a=function(a){var b=bi(a);return $CLJS.q(b)?b:Hl.a(a)};$CLJS.oi.b=function(a,b){var c=bi(a);return $CLJS.q(c)?c:Hl.b(a,b)};$CLJS.oi.A=2;$CLJS.Il=new $CLJS.Ka(null,4,[vk,$CLJS.Ge,Yk,$CLJS.nh,Mk,$CLJS.Qb,$CLJS.el,$CLJS.Sd],null);
$CLJS.Jl=function Jl(a){var c=null!=a&&(a.g&64||$CLJS.Gb===a.T)?$CLJS.Gd($CLJS.Ui,a):a,d=$CLJS.N.b(c,$CLJS.fj);a=$CLJS.F(d);var e=$CLJS.H(a);a=$CLJS.K(a);var f=$CLJS.N.b(c,$CLJS.gj),g=$CLJS.F(f),k=$CLJS.H(g);g=$CLJS.K(g);var l=$CLJS.N.b(c,$CLJS.Zi),m=$CLJS.F(l);$CLJS.H(m);m=$CLJS.K(m);var n=$CLJS.N.b(c,$CLJS.Si);c=$CLJS.N.b(c,oj);return $CLJS.Ud($CLJS.$c,d)?Vi(e)?(d=$CLJS.Si.a(e),d=$CLJS.fh.b(n,$CLJS.q(f)?$CLJS.$e([k,d]):d),a?(a=new $CLJS.Ka(null,4,[$CLJS.fj,a,$CLJS.gj,g,$CLJS.Zi,m,$CLJS.Si,d],null),
Jl.a?Jl.a(a):Jl(a)):$CLJS.Ti(d)):new $CLJS.Ka(null,6,[ci,mj,$CLJS.fj,d,$CLJS.Si,n,$CLJS.gj,f,$CLJS.Zi,l,oj,c],null):null};
zj=function zj(a){a=ai(a);var c=null!=a&&(a.g&64||$CLJS.Gb===a.T)?$CLJS.Gd($CLJS.Ui,a):a,d=$CLJS.N.b(c,ci),e=$CLJS.N.b(c,$CLJS.fj);a=$CLJS.N.b(c,aj);var f=$CLJS.N.b(c,Xi);c=$CLJS.N.b(c,$CLJS.Zi);if($CLJS.M.b(Ri,d))return!0;if($CLJS.M.b(null,d))return null;if($CLJS.M.b(lj,d))return d=zj.a?zj.a(a):zj(a),$CLJS.q(d)?(a=Pi(jj(a),e,$CLJS.K(c)),!$CLJS.mi(a)):d;if($CLJS.M.b(Wi,d))return(e=a===f)?e:zj.a?zj.a(a):zj(a);if($CLJS.M.b(mj,d))return $CLJS.Ud(zj,e);if($CLJS.M.b(ej,d))return $CLJS.Fh(zj,e);throw Error(["No matching clause: ",
$CLJS.z.a(d)].join(""));};
jj=function jj(a){a=ai(a);var c=null!=a&&(a.g&64||$CLJS.Gb===a.T)?$CLJS.Gd($CLJS.Ui,a):a;a=$CLJS.N.b(c,$CLJS.fj);var d=$CLJS.F(a),e=$CLJS.H(d);$CLJS.K(d);var f=$CLJS.N.b(c,$CLJS.gj),g=$CLJS.uc(f,0,null),k=$CLJS.N.b(c,ci);d=$CLJS.N.b(c,aj);var l=$CLJS.N.b(c,$CLJS.Si);c=$CLJS.N.b(c,$CLJS.Zi);if($CLJS.M.b(Ri,k))return l;if($CLJS.M.b(null,k))return null;if($CLJS.M.b(lj,k))return e=jj.a?jj.a(d):jj(d),(f=$CLJS.M.b(e,$CLJS.kj))?d=f:(d=ci.a(ai(d)),f=new $CLJS.Pf(null,new $CLJS.Ka(null,2,[Wi,null,mj,null],
null),null),d=f.a?f.a(d):f(d),d=$CLJS.q(d)?$CLJS.Ac(e):d,d=$CLJS.q(d)?d:null),$CLJS.q(d)?$CLJS.kj:Pi(e,a,c);if($CLJS.M.b(Wi,k))return nj(d,l,g);if($CLJS.M.b(mj,k))return nj(e,l,g);if($CLJS.M.b(ej,k))return c=dj(a,f,c,zj),a=$CLJS.uc(c,0,null),a=$CLJS.uc(a,0,null),c=$CLJS.uc(c,1,null),c=$CLJS.uc(c,0,null),a=null==a?$CLJS.kj:jj.a?jj.a(a):jj(a),$CLJS.q(c)?$CLJS.Oi(c,a):a;throw Error(["No matching clause: ",$CLJS.z.a(k)].join(""));};
Aj=function Aj(a,b){var d=ai(a),e=null!=d&&(d.g&64||$CLJS.Gb===d.T)?$CLJS.Gd($CLJS.Ui,d):d,f=$CLJS.N.b(e,$CLJS.Zi),g=$CLJS.N.b(e,Xi);a=$CLJS.N.b(e,$CLJS.fj);var k=$CLJS.F(a),l=$CLJS.H(k),m=$CLJS.K(k),n=$CLJS.N.b(e,$CLJS.Si),p=$CLJS.N.b(e,ci),v=$CLJS.N.b(e,Yi),u=$CLJS.N.b(e,$CLJS.gj),x=$CLJS.F(u),D=$CLJS.H(x),I=$CLJS.K(x),O=$CLJS.N.b(e,qj),U=$CLJS.N.b(e,aj);if($CLJS.q(e)){if($CLJS.M.b(Ri,p))return null;if($CLJS.M.b(null,p))return a=$CLJS.yi(e,b,e,null),$CLJS.mi(a)?null:$CLJS.Ti(a);if($CLJS.M.b(lj,
p))return d=Aj.b?Aj.b(U,b):Aj(U,b),$CLJS.q(d)?$CLJS.M.b(Ri,ci.a(d))?(a=Pi(jj(d),a,$CLJS.K(f)),$CLJS.mi(a)?null:$CLJS.Ti(a)):new $CLJS.Ka(null,5,[ci,lj,aj,d,qj,O,$CLJS.fj,a,$CLJS.Zi,f],null):null;if($CLJS.M.b(mj,p))return ij($CLJS.Jl(new $CLJS.Ka(null,4,[$CLJS.fj,$CLJS.jd(Aj.b?Aj.b(l,b):Aj(l,b),m),$CLJS.gj,u,$CLJS.Zi,f,$CLJS.Si,n],null)),$CLJS.q(zj(l))?function(){var Y=$CLJS.Jl(new $CLJS.Ka(null,4,[$CLJS.fj,m,$CLJS.gj,I,$CLJS.Zi,$CLJS.K(f),$CLJS.Si,nj(l,n,D)],null));return Aj.b?Aj.b(Y,b):Aj(Y,b)}():
null);if($CLJS.M.b(ej,p))return $CLJS.hj($CLJS.he.b(function(){return function(Y){return Aj.b?Aj.b(Y,b):Aj(Y,b)}}(p,d,e,e,f,g,a,k,l,m,l,m,a,n,p,v,u,x,D,I,D,I,u,O,U),a),u,f);if($CLJS.M.b(Wi,p))return ij(bj(Aj.b?Aj.b(U,b):Aj(U,b),g,n,v,f),$CLJS.q(zj(U))?function(){var Y=bj(g,g,nj(U,n,null),v,f);return Aj.b?Aj.b(Y,b):Aj(Y,b)}():null);throw Error(["No matching clause: ",$CLJS.z.a(p)].join(""));}return null};
Kl=function Kl(a,b,c,d,e,f){var k=$CLJS.uc(f,0,null),l=ai(b),m=null!=l&&(l.g&64||$CLJS.Gb===l.T)?$CLJS.Gd($CLJS.Ui,l):l,n=$CLJS.N.b(m,ci),p=$CLJS.N.b(m,$CLJS.fj),v=$CLJS.N.b(m,$CLJS.gj),u=$CLJS.N.b(m,$CLJS.Zi),x=$CLJS.N.b(m,Yi),D=$CLJS.N.b(m,aj),I=$CLJS.N.b(m,Xi);b=function(){var U=$CLJS.gi(m);return $CLJS.q(U)?$CLJS.fh.b(d,U):d}();var O=function(U,Y,ea,na,da,r,w,t,y,A,B,E,G,J){return function(P,S){return new $CLJS.R(null,1,5,$CLJS.T,[new $CLJS.Ka(null,6,[$CLJS.Ai,P,$CLJS.yl,"Insufficient input",
$CLJS.Bi,S,$CLJS.Hg,$CLJS.Qb,$CLJS.Ci,J,$CLJS.Di,e],null)],null)}}(f,k,f,l,m,m,n,p,v,u,x,D,I,b);if($CLJS.q(m)){if($CLJS.M.b(Ri,n))return null;if($CLJS.M.b(null,n))return $CLJS.Ac(f)?O(c,a):$CLJS.Ei(a,m,c,b,e,k);if($CLJS.M.b(lj,n)){if($CLJS.Ac(f))return $CLJS.q(zj(D))?$CLJS.Qi(u,p,c,b,e,jj(D)):O(c,qj.a(m));O=Aj(D,k);if($CLJS.q(O))return $CLJS.Qi(u,p,c,b,e,jj(O));O=qj.a(m);return Kl.S?Kl.S(O,D,c,b,e,f):Kl(O,D,c,b,e,f)}if($CLJS.M.b(mj,n))return a=$CLJS.he.s($CLJS.cj,p,function(){var U=$CLJS.F(v);return U?
U:$CLJS.de(null)}(),function(){var U=$CLJS.F(u);return U?U:$CLJS.de(null)}()),p=$CLJS.M.b(1,$CLJS.ic(a))?$CLJS.H(a):$CLJS.H($CLJS.Xh(function(){return function(U){U=$CLJS.uc(U,0,null);return zj(U)}}(a,n,f,k,f,l,m,m,n,p,v,u,x,D,I,b,O),a)),D=$CLJS.uc(p,0,null),k=$CLJS.uc(p,1,null),p=$CLJS.uc(p,2,null),k=$CLJS.q(k)?$CLJS.fh.b(c,k):c,p=$CLJS.q(p)?p:yj(D),$CLJS.Ac(f)&&$CLJS.Ya(D)?O(k,p):Kl.S?Kl.S(p,D,k,b,e,f):Kl(p,D,k,b,e,f);if($CLJS.M.b(ej,n))return $CLJS.Ac(f)?O(c,yj(m)):$CLJS.Gd($CLJS.ge,$CLJS.he.s(function(U,
Y,ea,na,da,r,w,t,y,A,B,E,G,J,P){return function(S,W,X){W=$CLJS.q(W)?W:yj(X);S=$CLJS.q(S)?$CLJS.fh.b(c,S):c;return Kl.S?Kl.S(W,X,S,P,e,na):Kl(W,X,S,P,e,na)}}(n,f,k,f,l,m,m,n,p,v,u,x,D,I,b,O),function(){var U=$CLJS.F(v);return U?U:$CLJS.de(null)}(),function(){var U=$CLJS.F(u);return U?U:$CLJS.de(null)}(),p));if($CLJS.M.b(Wi,n))return O=D===I?u:yj(D),Kl.S?Kl.S(O,D,c,b,e,f):Kl(O,D,c,b,e,f);throw Error(["No matching clause: ",$CLJS.z.a(n)].join(""));}return null};
hi=function hi(a,b){if("undefined"===typeof $CLJS.Nd||"undefined"===typeof $CLJS.Gi||"undefined"===typeof $CLJS.Hi||"undefined"===typeof Gl)Gl=function(d,e,f){this.Kb=d;this.Ha=e;this.ld=f;this.g=393216;this.w=0},Gl.prototype.K=function(d,e){return new Gl(this.Kb,this.Ha,e)},Gl.prototype.J=function(){return this.ld},Gl.prototype.Pa=function(){return this},Gl.prototype.Qa=function(){return this},Gl.prototype.vb=$CLJS.Gb,Gl.prototype.ib=function(d,e){return null==e||$CLJS.Cc(e)?Bj(this.Kb,$CLJS.F(e)):
$CLJS.li},Gl.prototype.jb=function(d,e,f,g,k){if(null==k||$CLJS.Cc(k))a:{d=this.Kb;var l=$CLJS.F(k);k=$CLJS.F(l);$CLJS.H(k);$CLJS.K(k);k=d;var m=l;for(l=0;;){var n=$CLJS.F(m),p=$CLJS.H(n);n=$CLJS.K(n);if($CLJS.Ac(m)){e=$CLJS.q(zj(k))?null:Kl(yj(k),k,e,f,g,null);break a}p=Aj(k,p);if($CLJS.q(p))m=n,l+=1,k=p;else{if(Vi(k)){e=$CLJS.M.b(ci.a(k),mj)?Kl(yj(k),k,e,f,$CLJS.fh.b(g,l),$CLJS.F(m)):new $CLJS.R(null,1,5,$CLJS.T,[new $CLJS.Ka(null,6,[$CLJS.Ai,e,$CLJS.yl,"Extra input",$CLJS.Bi,yj(d),$CLJS.Hg,m,$CLJS.Ci,
f,$CLJS.Di,$CLJS.fh.b(g,l)],null)],null);break a}d=Kl(yj(k),k,e,f,$CLJS.fh.b(g,l),$CLJS.F(m));e=$CLJS.q(d)?d:new $CLJS.R(null,1,5,$CLJS.T,[new $CLJS.Ka(null,6,[$CLJS.Ai,e,$CLJS.yl,"Extra input",$CLJS.Bi,yj(k),$CLJS.Hg,m,$CLJS.Ci,f,$CLJS.Di,$CLJS.fh.b(g,l)],null)],null);break a}}}else e=new $CLJS.R(null,1,5,$CLJS.T,[new $CLJS.Ka(null,5,[$CLJS.Ai,e,$CLJS.Bi,$CLJS.Dh($CLJS.F($CLJS.ge.j(new $CLJS.fd(null,$CLJS.Wj,null,1,null),new $CLJS.fd(null,$CLJS.He($CLJS.Dh($CLJS.F($CLJS.ge.a(new $CLJS.fd(null,$CLJS.ul,
null,1,null))))),null,1,null),$CLJS.pc([new $CLJS.fd(null,$CLJS.Dh($CLJS.F($CLJS.ge.j(new $CLJS.fd(null,$CLJS.Bk,null,1,null),new $CLJS.fd(null,$CLJS.Dh($CLJS.F($CLJS.ge.b(new $CLJS.fd(null,sl,null,1,null),new $CLJS.fd(null,$CLJS.ul,null,1,null)))),null,1,null),$CLJS.pc([new $CLJS.fd(null,$CLJS.Dh($CLJS.F($CLJS.ge.b(new $CLJS.fd(null,tl,null,1,null),new $CLJS.fd(null,$CLJS.ul,null,1,null)))),null,1,null)])))),null,1,null)])))),$CLJS.Hg,k,$CLJS.Ci,f,$CLJS.Di,g],null)],null);return e},Gl.prototype.kb=
function(d,e){return hi.b?hi.b(this.Kb,e):hi(this.Kb,e)},Gl.yb=function(){return new $CLJS.R(null,3,5,$CLJS.T,[Rk,$CLJS.Ki,kl],null)},Gl.ab=!0,Gl.Oa="cljs.spec.alpha/t_cljs$spec$alpha8922",Gl.hb=function(d,e){return $CLJS.Rd(e,"cljs.spec.alpha/t_cljs$spec$alpha8922")};return new Gl(a,b,$CLJS.Sd)};
$CLJS.xi(Lj,$CLJS.V($CLJS.Lk,$CLJS.V($CLJS.Ig,new $CLJS.R(null,1,5,$CLJS.T,[Ej],null),$CLJS.V(Hj,$CLJS.V(il,ql,Ej),$CLJS.V(il,pl,Ej))),$CLJS.V($CLJS.Ig,new $CLJS.R(null,1,5,$CLJS.T,[mk],null),$CLJS.V(il,$CLJS.V($CLJS.Wj,new $CLJS.R(null,1,5,$CLJS.T,[new $CLJS.R(null,2,5,$CLJS.T,[Nk,$CLJS.Og],null)],null),new $CLJS.Ka(null,2,[ql,Nk,pl,$CLJS.Og],null)),mk))),Fi($CLJS.V($CLJS.Lk,$CLJS.V($CLJS.Wj,new $CLJS.R(null,1,5,$CLJS.T,[$CLJS.ul],null),$CLJS.V(Hj,$CLJS.V(il,ql,$CLJS.ul),$CLJS.V(il,pl,$CLJS.ul))),
$CLJS.V($CLJS.Wj,new $CLJS.R(null,1,5,$CLJS.T,[$CLJS.ul],null),$CLJS.V(il,$CLJS.V($CLJS.Wj,new $CLJS.R(null,1,5,$CLJS.T,[new $CLJS.R(null,2,5,$CLJS.T,[Nk,$CLJS.Og],null)],null),new $CLJS.Ka(null,2,[ql,Nk,pl,$CLJS.Og],null)),$CLJS.ul))),function(a){return $CLJS.Eh($CLJS.he.b(ql,a),$CLJS.he.b(pl,a))},null,!0,function(a){return $CLJS.he.b(function(b){var c=$CLJS.uc(b,0,null);b=$CLJS.uc(b,1,null);return new $CLJS.Ka(null,2,[ql,c,pl,b],null)},a)}));
if("undefined"===typeof $CLJS.Nd||"undefined"===typeof $CLJS.Gi||"undefined"===typeof $CLJS.Hi||"undefined"===typeof Ll)var Ll=!1;if("undefined"===typeof $CLJS.Nd||"undefined"===typeof $CLJS.Gi||"undefined"===typeof $CLJS.Hi||"undefined"===typeof Ml)var Ml=!1;