var window=global;var $CLJS=require("./cljs_env");require("./goog.base.js");require("./cljs.core.js");require("./clojure.string.js");
$CLJS.oD=new $CLJS.Q("devtools.munging","multi-arity","devtools.munging/multi-arity",-2011705837);$CLJS.pD=new $CLJS.Q(null,"fast?","fast?",-1813307150);$CLJS.qD=new $CLJS.Q("devtools.munging","result","devtools.munging/result",1642759166);$CLJS.rD=new $CLJS.Q(null,"naked","naked",373474222);$CLJS.sD=new $CLJS.Q("devtools.munging","variadic","devtools.munging/variadic",1596047908);$CLJS.tD=new $CLJS.nm(function(){return new $CLJS.Ka(null,2,[0,$CLJS.rh([8192,4096,524288,128,1048576,1,32768,4,268435456,512,33554432,32,256,1024,134217728,16777216,64,262144,2,4194304,131072,67108864,8388608,16,2097152,1073741824,2147483648,2048,8,65536,16384],[new $CLJS.R(null,3,5,$CLJS.T,["cljs.core","IStack","cljs.core.IStack"],null),new $CLJS.R(null,3,5,$CLJS.T,["cljs.core","ISet","cljs.core.ISet"],null),new $CLJS.R(null,3,5,$CLJS.T,["cljs.core","IReduce","cljs.core.IReduce"],null),new $CLJS.R(null,
3,5,$CLJS.T,["cljs.core","INext","cljs.core.INext"],null),new $CLJS.R(null,3,5,$CLJS.T,["cljs.core","IKVReduce","cljs.core.IKVReduce"],null),new $CLJS.R(null,3,5,$CLJS.T,["cljs.core","IFn","cljs.core.IFn"],null),new $CLJS.R(null,3,5,$CLJS.T,["cljs.core","IDeref","cljs.core.IDeref"],null),new $CLJS.R(null,3,5,$CLJS.T,["cljs.core","IEmptyableCollection","cljs.core.IEmptyableCollection"],null),new $CLJS.R(null,3,5,$CLJS.T,["cljs.core","ISorted","cljs.core.ISorted"],null),new $CLJS.R(null,3,5,$CLJS.T,
["cljs.core","IAssociative","cljs.core.IAssociative"],null),new $CLJS.R(null,3,5,$CLJS.T,["cljs.core","IList","cljs.core.IList"],null),new $CLJS.R(null,3,5,$CLJS.T,["cljs.core","ASeq","cljs.core.ASeq"],null),new $CLJS.R(null,3,5,$CLJS.T,["cljs.core","ILookup","cljs.core.ILookup"],null),new $CLJS.R(null,3,5,$CLJS.T,["cljs.core","IMap","cljs.core.IMap"],null),new $CLJS.R(null,3,5,$CLJS.T,["cljs.core","IReversible","cljs.core.IReversible"],null),new $CLJS.R(null,3,5,$CLJS.T,["cljs.core","ISequential",
"cljs.core.ISequential"],null),new $CLJS.R(null,3,5,$CLJS.T,["cljs.core","ISeq","cljs.core.ISeq"],null),new $CLJS.R(null,3,5,$CLJS.T,["cljs.core","IWithMeta","cljs.core.IWithMeta"],null),new $CLJS.R(null,3,5,$CLJS.T,["cljs.core","ICounted","cljs.core.ICounted"],null),new $CLJS.R(null,3,5,$CLJS.T,["cljs.core","IHash","cljs.core.IHash"],null),new $CLJS.R(null,3,5,$CLJS.T,["cljs.core","IMeta","cljs.core.IMeta"],null),new $CLJS.R(null,3,5,$CLJS.T,["cljs.core","IRecord","cljs.core.IRecord"],null),new $CLJS.R(null,
3,5,$CLJS.T,["cljs.core","ISeqable","cljs.core.ISeqable"],null),new $CLJS.R(null,3,5,$CLJS.T,["cljs.core","IIndexed","cljs.core.IIndexed"],null),new $CLJS.R(null,3,5,$CLJS.T,["cljs.core","IEquiv","cljs.core.IEquiv"],null),new $CLJS.R(null,3,5,$CLJS.T,["cljs.core","IWriter","cljs.core.IWriter"],null),new $CLJS.R(null,3,5,$CLJS.T,["cljs.core","IPrintWithWriter","cljs.core.IPrintWithWriter"],null),new $CLJS.R(null,3,5,$CLJS.T,["cljs.core","IMapEntry","cljs.core.IMapEntry"],null),new $CLJS.R(null,3,5,
$CLJS.T,["cljs.core","ICollection","cljs.core.ICollection"],null),new $CLJS.R(null,3,5,$CLJS.T,["cljs.core","IDerefWithTimeout","cljs.core.IDerefWithTimeout"],null),new $CLJS.R(null,3,5,$CLJS.T,["cljs.core","IVector","cljs.core.IVector"],null)]),1,$CLJS.rh([8192,4096,128,1,32768,4,512,32,256,1024,64,2,131072,16,2048,8,65536,16384],[new $CLJS.R(null,3,5,$CLJS.T,["cljs.core","ICloneable","cljs.core.ICloneable"],null),new $CLJS.R(null,3,5,$CLJS.T,["cljs.core","INamed","cljs.core.INamed"],null),new $CLJS.R(null,
3,5,$CLJS.T,["cljs.core","ITransientSet","cljs.core.ITransientSet"],null),new $CLJS.R(null,3,5,$CLJS.T,["cljs.core","IPending","cljs.core.IPending"],null),new $CLJS.R(null,3,5,$CLJS.T,["cljs.core","IReset","cljs.core.IReset"],null),new $CLJS.R(null,3,5,$CLJS.T,["cljs.core","IEditableCollection","cljs.core.IEditableCollection"],null),new $CLJS.R(null,3,5,$CLJS.T,["cljs.core","IChunkedSeq","cljs.core.IChunkedSeq"],null),new $CLJS.R(null,3,5,$CLJS.T,["cljs.core","ITransientMap","cljs.core.ITransientMap"],
null),new $CLJS.R(null,3,5,$CLJS.T,["cljs.core","IMultiFn","cljs.core.IMultiFn"],null),new $CLJS.R(null,3,5,$CLJS.T,["cljs.core","IChunkedNext","cljs.core.IChunkedNext"],null),new $CLJS.R(null,3,5,$CLJS.T,["cljs.core","ITransientVector","cljs.core.ITransientVector"],null),new $CLJS.R(null,3,5,$CLJS.T,["cljs.core","IWatchable","cljs.core.IWatchable"],null),new $CLJS.R(null,3,5,$CLJS.T,["cljs.core","IIterable","cljs.core.IIterable"],null),new $CLJS.R(null,3,5,$CLJS.T,["cljs.core","ITransientAssociative",
"cljs.core.ITransientAssociative"],null),new $CLJS.R(null,3,5,$CLJS.T,["cljs.core","IComparable","cljs.core.IComparable"],null),new $CLJS.R(null,3,5,$CLJS.T,["cljs.core","ITransientCollection","cljs.core.ITransientCollection"],null),new $CLJS.R(null,3,5,$CLJS.T,["cljs.core","ISwap","cljs.core.ISwap"],null),new $CLJS.R(null,3,5,$CLJS.T,["cljs.core","IAtom","cljs.core.IAtom"],null)])],null)});