var window=global;var $CLJS=require("./cljs_env");require("./goog.base.js");require("./cljs.core.js");require("./graphql_query.spec.js");require("./clojure.string.js");require("./goog.string.internal.js");
var dr,er,fr,hr,ir,jr;
dr=function(a){return $CLJS.Gd($CLJS.z,$CLJS.le($CLJS.fe(",",function(){return function d(c){return new $CLJS.od(null,function(){for(;;){var e=$CLJS.F(c);if(e){if($CLJS.Gc(e)){var f=$CLJS.Xd(e),g=$CLJS.ic(f),k=$CLJS.sd(g);a:for(var l=0;;)if(l<g){var m=$CLJS.bc.b(f,l),n=$CLJS.uc(m,0,null);m=$CLJS.uc(m,1,null);n=new $CLJS.R(null,3,5,$CLJS.T,[$CLJS.mp.a?$CLJS.mp.a(n):(0,$CLJS.mp)(n),":",cr(m)],null);k.add(n);l+=1}else{f=!0;break a}return f?$CLJS.vd(k.$(),d($CLJS.Yd(e))):$CLJS.vd(k.$(),null)}f=$CLJS.H(e);
k=$CLJS.uc(f,0,null);f=$CLJS.uc(f,1,null);return $CLJS.jd(new $CLJS.R(null,3,5,$CLJS.T,[$CLJS.mp.a?$CLJS.mp.a(k):(0,$CLJS.mp)(k),":",cr(f)],null),d($CLJS.Rb(e)))}return null}},null)}(a)}())))};er=function(a){return["[",$CLJS.z.a($CLJS.Gd($CLJS.z,$CLJS.fe(",",$CLJS.he.b(cr,a)))),"]"].join("")};
fr=function(a){return $CLJS.Gd($CLJS.z,$CLJS.fe(",",function(){return function d(c){return new $CLJS.od(null,function(){for(;;){var e=$CLJS.F(c);if(e){if($CLJS.Gc(e)){var f=$CLJS.Xd(e),g=$CLJS.ic(f),k=$CLJS.sd(g);a:for(var l=0;;)if(l<g){var m=$CLJS.bc.b(f,l),n=null!=m&&(m.g&64||$CLJS.Gb===m.T)?$CLJS.Gd($CLJS.Ui,m):m;m=$CLJS.N.b(n,$CLJS.An);var p=$CLJS.N.b(n,$CLJS.Vm);n=$CLJS.N.b(n,$CLJS.Zm);m=[$CLJS.Sf(m),":",$CLJS.z.a($CLJS.mp.a?$CLJS.mp.a(p):(0,$CLJS.mp)(p)),$CLJS.q(n)?["\x3d",$CLJS.z.a(cr(n))].join(""):
null].join("");k.add(m);l+=1}else{f=!0;break a}return f?$CLJS.vd(k.$(),d($CLJS.Yd(e))):$CLJS.vd(k.$(),null)}k=$CLJS.H(e);g=null!=k&&(k.g&64||$CLJS.Gb===k.T)?$CLJS.Gd($CLJS.Ui,k):k;k=$CLJS.N.b(g,$CLJS.An);f=$CLJS.N.b(g,$CLJS.Vm);g=$CLJS.N.b(g,$CLJS.Zm);return $CLJS.jd([$CLJS.Sf(k),":",$CLJS.z.a($CLJS.mp.a?$CLJS.mp.a(f):(0,$CLJS.mp)(f)),$CLJS.q(g)?["\x3d",$CLJS.z.a(cr(g))].join(""):null].join(""),d($CLJS.Rb(e)))}return null}},null)}(a)}()))};
hr=function(a){var b=["{",$CLJS.z.a(gr($CLJS.fn.a(a))),"}"].join("");return["fragment ",$CLJS.z.a(function(){var c=$CLJS.Sf($CLJS.Dn.a(a));return $CLJS.mp.a?$CLJS.mp.a(c):(0,$CLJS.mp)(c)}())," on ",$CLJS.z.a(function(){var c=$CLJS.Nn.a(a);return $CLJS.mp.a?$CLJS.mp.a(c):(0,$CLJS.mp)(c)}()),b].join("")};ir=function(a){return a instanceof $CLJS.Q||!$CLJS.Ac(a)};jr=new $CLJS.Q("graphql-query","query-vector","graphql-query/query-vector",-1817956937);
$CLJS.kr=new $CLJS.Q(null,"kw-\x3egql-name","kw-\x3egql-name",-1726890150);var lr,cr;lr={};$CLJS.mp=$CLJS.Sf;cr=function cr(a){if(null!=a&&null!=a.cb)return a.cb(a);var c=cr[$CLJS.Ca(null==a?null:a)];if(null!=c)return c.a?c.a(a):c(a);c=cr._;if(null!=c)return c.a?c.a(a):c(a);throw $CLJS.ab("ArgumentFormatter.arg-\x3estr",a);};cr["null"]=function(){return"null"};$CLJS.Nb.prototype.cb=function(){return er(this)};$CLJS.od.prototype.cb=function(){return er(this)};cr["boolean"]=function(a){return $CLJS.z.a(a)};cr.object=function(a){return $CLJS.z.a(a)};cr.number=function(a){return $CLJS.z.a(a)};
$CLJS.Ff.prototype.cb=function(){return["{",$CLJS.z.a(dr(this)),"}"].join("")};$CLJS.R.prototype.cb=function(){return er(this)};cr.string=function(a){return['"',$CLJS.z.a(a),'"'].join("")};$CLJS.Q.prototype.cb=function(){return $CLJS.mp.a?$CLJS.mp.a(this):(0,$CLJS.mp)(this)};$CLJS.Ka.prototype.cb=function(){return["{",$CLJS.z.a(dr(this)),"}"].join("")};$CLJS.fd.prototype.cb=function(){return er(this)};
var gr=function gr(a){return a instanceof $CLJS.Q?["...",$CLJS.z.a(function(){var c=$CLJS.Sf(a);return $CLJS.mp.a?$CLJS.mp.a(c):(0,$CLJS.mp)(c)}())].join(""):$CLJS.Gd($CLJS.z,$CLJS.fe(",",function(){return function e(d){return new $CLJS.od(null,function(){for(;;){var f=$CLJS.F(d);if(f){var g=f;if($CLJS.Gc(g)){var k=$CLJS.Xd(g),l=$CLJS.ic(k),m=$CLJS.sd(l);return function(){for(var u=0;;)if(u<l){var x=$CLJS.bc.b(k,u),D=$CLJS.uc(x,0,null),I=$CLJS.uc(x,1,null);$CLJS.wd(m,function(){var O=D;if($CLJS.q($CLJS.M.b?
$CLJS.M.b($CLJS.Xn,O):$CLJS.M($CLJS.Xn,O)))return["__",$CLJS.Sf(I)].join("");if($CLJS.q($CLJS.M.b?$CLJS.M.b($CLJS.$n,O):$CLJS.M($CLJS.$n,O)))return $CLJS.mp.a?$CLJS.mp.a(I):(0,$CLJS.mp)(I);if($CLJS.q($CLJS.M.b?$CLJS.M.b($CLJS.tn,O):$CLJS.M($CLJS.tn,O)))return[$CLJS.z.a(function(){var U=$CLJS.$n.a(I);return $CLJS.mp.a?$CLJS.mp.a(U):(0,$CLJS.mp)(U)}()),$CLJS.q($CLJS.jl.a(I))?["(",$CLJS.z.a(dr($CLJS.jl.a(I))),")"].join(""):null].join("");if($CLJS.q($CLJS.M.b?$CLJS.M.b($CLJS.Bn,O):$CLJS.M($CLJS.Bn,O)))return[function(){var U=
$CLJS.qn.a(I);U=$CLJS.mp.a?$CLJS.mp.a(U):(0,$CLJS.mp)(U);return $CLJS.q(U)?[$CLJS.z.a(U),":"].join(""):null}(),$CLJS.z.a(function(){var U=$CLJS.Tn.a(I);return gr.a?gr.a(U):gr(U)}())].join("");if($CLJS.q($CLJS.M.b?$CLJS.M.b($CLJS.ho,O):$CLJS.M($CLJS.ho,O)))return[$CLJS.z.a(function(){var U=$CLJS.fo.a(I);return $CLJS.mp.a?$CLJS.mp.a(U):(0,$CLJS.mp)(U)}()),$CLJS.q($CLJS.jl.a(I))?["(",$CLJS.z.a(dr($CLJS.jl.a(I))),")"].join(""):null,"{",$CLJS.z.a(function(){var U=$CLJS.jn.a(I);return gr.a?gr.a(U):gr(U)}()),
"}"].join("");if($CLJS.q($CLJS.M.b?$CLJS.M.b($CLJS.Hn,O):$CLJS.M($CLJS.Hn,O)))return[$CLJS.z.a(function(){var U=$CLJS.fo.a(I);return $CLJS.mp.a?$CLJS.mp.a(U):(0,$CLJS.mp)(U)}()),["(",$CLJS.z.a(dr($CLJS.jl.a(I))),")"].join("")].join("");if($CLJS.q($CLJS.M.b?$CLJS.M.b($CLJS.hn,O):$CLJS.M($CLJS.hn,O)))return $CLJS.Hh(" ",$CLJS.he.b(function(){return function(U){return["...",$CLJS.z.a(function(){var Y=$CLJS.Sf(U);return $CLJS.mp.a?$CLJS.mp.a(Y):(0,$CLJS.mp)(Y)}())].join("")}}(u,$CLJS.M,O,x,D,I,k,l,m,
g,f),I));if($CLJS.q($CLJS.M.b?$CLJS.M.b($CLJS.Vn,O):$CLJS.M($CLJS.Vn,O)))return[$CLJS.z.a(function(){var U=$CLJS.fo.a(I);return $CLJS.mp.a?$CLJS.mp.a(U):(0,$CLJS.mp)(U)}()),"{",$CLJS.z.a($CLJS.Hh(" ",$CLJS.he.b(function(){return function(U){return["...",$CLJS.z.a(function(){var Y=$CLJS.Sf(U);return $CLJS.mp.a?$CLJS.mp.a(Y):(0,$CLJS.mp)(Y)}())].join("")}}(u,$CLJS.M,O,x,D,I,k,l,m,g,f),$CLJS.hn.a(I)))),"}"].join("");throw Error(["No matching clause: ",$CLJS.z.a(O)].join(""));}());u+=1}else return!0}()?
$CLJS.vd(m.$(),e($CLJS.Yd(g))):$CLJS.vd(m.$(),null)}var n=$CLJS.H(g),p=$CLJS.uc(n,0,null),v=$CLJS.uc(n,1,null);return $CLJS.jd(function(){var u=p;if($CLJS.q($CLJS.M.b?$CLJS.M.b($CLJS.Xn,u):$CLJS.M($CLJS.Xn,u)))return["__",$CLJS.Sf(v)].join("");if($CLJS.q($CLJS.M.b?$CLJS.M.b($CLJS.$n,u):$CLJS.M($CLJS.$n,u)))return $CLJS.mp.a?$CLJS.mp.a(v):(0,$CLJS.mp)(v);if($CLJS.q($CLJS.M.b?$CLJS.M.b($CLJS.tn,u):$CLJS.M($CLJS.tn,u)))return[$CLJS.z.a(function(){var x=$CLJS.$n.a(v);return $CLJS.mp.a?$CLJS.mp.a(x):(0,$CLJS.mp)(x)}()),
$CLJS.q($CLJS.jl.a(v))?["(",$CLJS.z.a(dr($CLJS.jl.a(v))),")"].join(""):null].join("");if($CLJS.q($CLJS.M.b?$CLJS.M.b($CLJS.Bn,u):$CLJS.M($CLJS.Bn,u)))return[function(){var x=$CLJS.qn.a(v);x=$CLJS.mp.a?$CLJS.mp.a(x):(0,$CLJS.mp)(x);return $CLJS.q(x)?[$CLJS.z.a(x),":"].join(""):null}(),$CLJS.z.a(function(){var x=$CLJS.Tn.a(v);return gr.a?gr.a(x):gr(x)}())].join("");if($CLJS.q($CLJS.M.b?$CLJS.M.b($CLJS.ho,u):$CLJS.M($CLJS.ho,u)))return[$CLJS.z.a(function(){var x=$CLJS.fo.a(v);return $CLJS.mp.a?$CLJS.mp.a(x):
(0,$CLJS.mp)(x)}()),$CLJS.q($CLJS.jl.a(v))?["(",$CLJS.z.a(dr($CLJS.jl.a(v))),")"].join(""):null,"{",$CLJS.z.a(function(){var x=$CLJS.jn.a(v);return gr.a?gr.a(x):gr(x)}()),"}"].join("");if($CLJS.q($CLJS.M.b?$CLJS.M.b($CLJS.Hn,u):$CLJS.M($CLJS.Hn,u)))return[$CLJS.z.a(function(){var x=$CLJS.fo.a(v);return $CLJS.mp.a?$CLJS.mp.a(x):(0,$CLJS.mp)(x)}()),["(",$CLJS.z.a(dr($CLJS.jl.a(v))),")"].join("")].join("");if($CLJS.q($CLJS.M.b?$CLJS.M.b($CLJS.hn,u):$CLJS.M($CLJS.hn,u)))return $CLJS.Hh(" ",$CLJS.he.b(function(){return function(x){return["...",
$CLJS.z.a(function(){var D=$CLJS.Sf(x);return $CLJS.mp.a?$CLJS.mp.a(D):(0,$CLJS.mp)(D)}())].join("")}}($CLJS.M,u,n,p,v,g,f),v));if($CLJS.q($CLJS.M.b?$CLJS.M.b($CLJS.Vn,u):$CLJS.M($CLJS.Vn,u)))return[$CLJS.z.a(function(){var x=$CLJS.fo.a(v);return $CLJS.mp.a?$CLJS.mp.a(x):(0,$CLJS.mp)(x)}()),"{",$CLJS.z.a($CLJS.Hh(" ",$CLJS.he.b(function(){return function(x){return["...",$CLJS.z.a(function(){var D=$CLJS.Sf(x);return $CLJS.mp.a?$CLJS.mp.a(D):(0,$CLJS.mp)(D)}())].join("")}}($CLJS.M,u,n,p,v,g,f),$CLJS.hn.a(v)))),
"}"].join("");throw Error(["No matching clause: ",$CLJS.z.a(u)].join(""));}(),e($CLJS.Rb(g)))}return null}},null)}(a)}()))};
if("undefined"===typeof $CLJS.Vl||"undefined"===typeof lr||"undefined"===typeof $CLJS.mr)$CLJS.mr=function(){var a=$CLJS.Wd($CLJS.Sd),b=$CLJS.Wd($CLJS.Sd),c=$CLJS.Wd($CLJS.Sd),d=$CLJS.Wd($CLJS.Sd),e=$CLJS.N.f($CLJS.Sd,$CLJS.Ql,$CLJS.ug.u?$CLJS.ug.u():$CLJS.ug());return new $CLJS.Dg($CLJS.ch.b("graphql-query.core","-\x3equery-str"),function(){return function(f){return $CLJS.Fc(f)?$CLJS.H(f):$CLJS.q($CLJS.bo.a(f))?$CLJS.bo:$CLJS.q($CLJS.hp.a(f))?$CLJS.hp:$CLJS.Cg}}(a,b,c,d,e),e,a,b,c,d)}();
$CLJS.mr.Vd(null,jr,function(a){$CLJS.uc(a,0,null);a=$CLJS.uc(a,1,null);return["{",$CLJS.z.a($CLJS.Gd($CLJS.z,$CLJS.fe(",",$CLJS.he.b($CLJS.mr,a)))),"}"].join("")});
$CLJS.mr.Vd(null,$CLJS.Qn,function(a){$CLJS.uc(a,0,null);a=$CLJS.uc(a,1,null);var b=$CLJS.Cn.a(a),c=$CLJS.q(b)?[$CLJS.z.a(function(){var f=$CLJS.xn.a(b);return $CLJS.mp.a?$CLJS.mp.a(f):(0,$CLJS.mp)(f)}())," ",$CLJS.z.a(function(){var f=$CLJS.Fn.a(b);return $CLJS.mp.a?$CLJS.mp.a(f):(0,$CLJS.mp)(f)}())].join(""):null,d=$CLJS.Ol.a(a);d=$CLJS.q(d)?["(",$CLJS.z.a(fr(d)),")"].join(""):null;var e=$CLJS.hn.a(a);e=$CLJS.q(e)?[" ",$CLJS.z.a($CLJS.Gd($CLJS.z,$CLJS.fe(",",$CLJS.he.b(hr,e))))].join(""):null;return[c,
d,"{",$CLJS.z.a($CLJS.Gd($CLJS.z,$CLJS.fe(",",$CLJS.he.b($CLJS.mr,$CLJS.Ym.a(a))))),"}",e].join("")});
$CLJS.mr.Vd(null,$CLJS.bo,function(a){var b=$CLJS.bo.a(a),c=$CLJS.q($CLJS.Wm.a(a))?[$CLJS.z.a(function(){var g=$CLJS.Wm.a(a);return $CLJS.mp.a?$CLJS.mp.a(g):(0,$CLJS.mp)(g)}()),":"].join(""):null,d=function(){var g=$CLJS.Rg.a(b);return $CLJS.mp.a?$CLJS.mp.a(g):(0,$CLJS.mp)(g)}(),e=$CLJS.q($CLJS.jl.a(b))?["(",$CLJS.z.a(dr($CLJS.jl.a(b))),")"].join(""):null,f=["{",$CLJS.z.a(gr($CLJS.Hm.a(b))),"}"].join("");return[c,$CLJS.z.a(d),e,f].join("")});
$CLJS.mr.Vd(null,$CLJS.Ym,function(a){$CLJS.uc(a,0,null);a=$CLJS.uc(a,1,null);return["{",$CLJS.z.a($CLJS.Gd($CLJS.z,$CLJS.fe(",",$CLJS.he.b($CLJS.mr,a)))),"}"].join("")});$CLJS.mr.Vd(null,$CLJS.hp,function(a){$CLJS.uc(a,0,null);var b=$CLJS.uc(a,1,null);a=function(){var c=$CLJS.Gm.a(b);return $CLJS.mr.a?$CLJS.mr.a(c):(0,$CLJS.mr)(c)}();return[$CLJS.q($CLJS.Wm.a(b))?[$CLJS.z.a(function(){var c=$CLJS.Wm.a(b);return $CLJS.mp.a?$CLJS.mp.a(c):(0,$CLJS.mp)(c)}()),":"].join(""):null,$CLJS.z.a(a)].join("")});
$CLJS.mr.Vd(null,$CLJS.Gm,function(a){$CLJS.uc(a,0,null);a=$CLJS.uc(a,1,null);var b=$CLJS.Rg.a(a);b=$CLJS.mp.a?$CLJS.mp.a(b):(0,$CLJS.mp)(b);var c=$CLJS.q($CLJS.jl.a(a))?["(",$CLJS.z.a(dr($CLJS.jl.a(a))),")"].join(""):null;a=ir($CLJS.Hm.a(a))?["{",$CLJS.z.a(gr($CLJS.Hm.a(a))),"}"].join(""):null;return[$CLJS.z.a(b),c,a].join("")});
$CLJS.mr.Vd(null,$CLJS.Cg,function(a){var b=$CLJS.Rg.a(a);b=$CLJS.mp.a?$CLJS.mp.a(b):(0,$CLJS.mp)(b);var c=$CLJS.q($CLJS.jl.a(a))?["(",$CLJS.z.a(dr($CLJS.jl.a(a))),")"].join(""):null;a=ir($CLJS.Hm.a(a))?["{",$CLJS.z.a(gr($CLJS.Hm.a(a))),"}"].join(""):null;return[$CLJS.z.a(b),c,a].join("")});