var window=global;var $CLJS=require("./cljs_env");require("./goog.base.js");require("./cljs.core.js");require("./graphql_cache.query.tools.js");require("./graphql_cache.query.interface.js");require("./graphql_cache.query.fetch_data.js");require("./graphql_cache.query.schema.js");
var Qo=function(){},Ro=function(){},So=function(a){a:for(var b=a;;)if(b=$CLJS.F(b))b=$CLJS.K(b);else break a;return a},To=function(a,b){return $CLJS.Lh(function(c,d){c=a.a?a.a(c):a(c);d=a.a?a.a(d):a(d);var e=$CLJS.Kh($CLJS.Mc);return e.b?e.b(c,d):e(c,d)},b)},Uo=function(a,b){return To(a,b)},Vo=function(a){$CLJS.ag("\n");return $CLJS.N.b(a,$CLJS.La),null},Wo=function(a,b){return $CLJS.xe($CLJS.Rc(function(c,d){return $CLJS.we.b(c,a.a?a.a(d):a(d))},$CLJS.Fe($CLJS.Ge),b))},Pp=function(a){function b(d,
e){d.push(e);return d}var c=[];return $CLJS.Rc?$CLJS.Rc(b,c,a):$CLJS.Sc(b,c,a)},Zo=function(a){var b=Yo;return $CLJS.q($CLJS.Fh($CLJS.$c,a))?$CLJS.Wc(function(c){return function(d,e){return $CLJS.Rc(c,$CLJS.q(d)?d:$CLJS.Sd,$CLJS.F(e))}}(function(c,d){var e=$CLJS.Be(d),f=$CLJS.De(d);return $CLJS.Kc(c,e)?$CLJS.kg.f(c,e,function(){var g=$CLJS.N.b(c,e);return b.b?b.b(g,f):b(g,f)}()):$CLJS.kg.f(c,e,f)}),a):null},$o=function(a,b,c){return function(){function d(m,n,p){return a.I?a.I(b,c,m,n,p):a(b,c,m,n,
p)}function e(m,n){return a.s?a.s(b,c,m,n):a(b,c,m,n)}function f(m){return a.f?a.f(b,c,m):a(b,c,m)}function g(){return a.b?a.b(b,c):a(b,c)}var k=null,l=function(){function m(p,v,u,x){var D=null;if(3<arguments.length){D=0;for(var I=Array(arguments.length-3);D<I.length;)I[D]=arguments[D+3],++D;D=new $CLJS.Nb(I,0,null)}return n.call(this,p,v,u,D)}function n(p,v,u,x){return $CLJS.Kd(a,b,c,p,v,$CLJS.pc([u,x]))}m.A=3;m.C=function(p){var v=$CLJS.H(p);p=$CLJS.K(p);var u=$CLJS.H(p);p=$CLJS.K(p);var x=$CLJS.H(p);
p=$CLJS.Rb(p);return n(v,u,x,p)};m.j=n;return m}();k=function(m,n,p,v){switch(arguments.length){case 0:return g.call(this);case 1:return f.call(this,m);case 2:return e.call(this,m,n);case 3:return d.call(this,m,n,p);default:var u=null;if(3<arguments.length){u=0;for(var x=Array(arguments.length-3);u<x.length;)x[u]=arguments[u+3],++u;u=new $CLJS.Nb(x,0,null)}return l.j(m,n,p,u)}throw Error("Invalid arity: "+arguments.length);};k.A=3;k.C=l.C;k.u=g;k.a=f;k.b=e;k.f=d;k.j=l.j;return k}()},ap=function(a,
b,c){if($CLJS.gd(c)){var d=$CLJS.Gd($CLJS.V,$CLJS.he.b(a,c));return b.a?b.a(d):b(d)}return $CLJS.ze(c)?(d=new $CLJS.Xe(function(){var e=$CLJS.Be(c);return a.a?a.a(e):a(e)}(),function(){var e=$CLJS.De(c);return a.a?a.a(e):a(e)}()),b.a?b.a(d):b(d)):$CLJS.Ch(c)?(d=So($CLJS.he.b(a,c)),b.a?b.a(d):b(d)):$CLJS.Ec(c)?(d=$CLJS.Rc(function(e,f){return $CLJS.fh.b(e,a.a?a.a(f):a(f))},c,c),b.a?b.a(d):b(d)):$CLJS.im(c)?(d=$CLJS.gh.b($CLJS.hm(c),$CLJS.he.b(a,c)),b.a?b.a(d):b(d)):b.a?b.a(c):b(c)},cp=function(a){return $CLJS.Ch(a)?
bp(function(b){var c=(c=b instanceof $CLJS.C)?$CLJS.md(b):c;return $CLJS.q(c)?$CLJS.ch.a($CLJS.Sf(b)):$CLJS.Ch(b)&&$CLJS.M.b($CLJS.Mg,$CLJS.H(b))&&$CLJS.M.b(new $CLJS.R(null,1,5,$CLJS.T,[$CLJS.ul],null),$CLJS.rc(b))?$CLJS.Qh(b):b},a):$CLJS.q(function(){var b=a instanceof $CLJS.C;return b?$CLJS.md(a):b}())?$CLJS.ch.a($CLJS.Sf(a)):a},Sp=function(a){var b=new $CLJS.Ka(null,2,["asc",$CLJS.Op,"desc",$CLJS.Rp],null);return bp(function(c){return $CLJS.Kc(b,c)?b.a?b.a(c):b(c):c},a)},gp=function(a,b){var c=
null!=b&&(b.g&64||$CLJS.Gb===b.T)?$CLJS.Gd($CLJS.Ui,b):b,d=$CLJS.N.b(c,$CLJS.Sg);return function(e,f,g,k){return function n(m){return(null!=m?$CLJS.Gb===m.Cd||(m.ic?0:$CLJS.Za(Ro,m)):$CLJS.Za(Ro,m))?ep(m,$CLJS.Gd(fp,b)):$CLJS.Ch(m)?So($CLJS.he.b(n,m)):$CLJS.ze(m)?new $CLJS.Xe(n($CLJS.Be(m)),n($CLJS.De(m))):$CLJS.im(m)?$CLJS.gh.f($CLJS.hm(m),$CLJS.he.a(n),m):$CLJS.Xa(m)?$CLJS.xe($CLJS.Rc(function(){return function(p,v){return $CLJS.we.b(p,n(v))}}(e,f,g,k),$CLJS.Fe($CLJS.Ge),m)):$CLJS.$a(m)===Object?
$CLJS.xe($CLJS.Rc(function(p,v,u,x){return function(D,I){return $CLJS.zd(D,x.a?x.a(I):x(I),n(null!==m&&I in m?m[I]:void 0))}}(e,f,g,k),$CLJS.Fe($CLJS.Sd),$CLJS.Ea(m))):m}}(b,c,d,$CLJS.q(d)?$CLJS.gg:$CLJS.z)(a)},Tp=function(a){$CLJS.og(a,$CLJS.Ra());$CLJS.Sa&&Vo($CLJS.Ra())},ip=function(a){$CLJS.og(a,$CLJS.Ra())},jp=function(a){if($CLJS.q(a)){var b=Uo(function(c){return-$CLJS.ic($CLJS.Ai.a(c))},Uo(function(c){return-$CLJS.ic($CLJS.Di.a(c))},$CLJS.Sk.a(a)));return $CLJS.oh.j($CLJS.pc([function(){var c=
new $CLJS.Ja,d=$CLJS.Sa,e=$CLJS.Ta,f=function(qb,jf,pi,ih){return function(Oj){return ih.append(Oj)}}(d,e,!0,c,b);$CLJS.Sa=!0;$CLJS.Ta=f;try{var g=$CLJS.F(b);f=null;for(var k=0,l=0;;)if(l<k){var m=f.O(null,l),n=null!=m&&(m.g&64||$CLJS.Gb===m.T)?$CLJS.Gd($CLJS.Ui,m):m,p=n,v=$CLJS.N.b(n,$CLJS.Ai),u=$CLJS.N.b(n,$CLJS.Bi),x=$CLJS.N.b(n,$CLJS.Hg),D=$CLJS.N.b(n,$CLJS.yl),I=$CLJS.N.b(n,$CLJS.Ci),O=$CLJS.N.b(n,$CLJS.Di);ip($CLJS.pc([x]));$CLJS.oh.j($CLJS.pc([" - failed: "]));$CLJS.q(D)?$CLJS.oh.j($CLJS.pc([D])):
ip($CLJS.pc([cp(u)]));$CLJS.Ac(O)||$CLJS.oh.j($CLJS.pc([[" in: ",$CLJS.Yh($CLJS.pc([O]))].join("")]));$CLJS.Ac(v)||$CLJS.oh.j($CLJS.pc([[" at: ",$CLJS.Yh($CLJS.pc([v]))].join("")]));$CLJS.Ac(I)||$CLJS.oh.j($CLJS.pc([[" spec: ",$CLJS.Yh($CLJS.pc([$CLJS.Qh(I)]))].join("")]));var U=$CLJS.F(p);p=null;for(var Y=0,ea=0;;)if(ea<Y){var na=p.O(null,ea),da=$CLJS.uc(na,0,null),r=$CLJS.uc(na,1,null);$CLJS.q(function(){var qb=new $CLJS.Pf(null,new $CLJS.Ka(null,6,[$CLJS.Ai,null,$CLJS.Bi,null,$CLJS.Ci,null,$CLJS.Hg,
null,$CLJS.yl,null,$CLJS.Di,null],null),null);return qb.a?qb.a(da):qb(da)}())||($CLJS.oh.j($CLJS.pc(["\n\t",$CLJS.Yh($CLJS.pc([da]))," "])),ip($CLJS.pc([r])));ea+=1}else{var w=$CLJS.F(U);if(w){var t=w;if($CLJS.Gc(t)){var y=$CLJS.Xd(t),A=$CLJS.Yd(t);t=y;var B=$CLJS.ic(y);U=A;p=t;Y=B}else{var E=$CLJS.H(t),G=$CLJS.uc(E,0,null),J=$CLJS.uc(E,1,null);$CLJS.q(function(){var qb=new $CLJS.Pf(null,new $CLJS.Ka(null,6,[$CLJS.Ai,null,$CLJS.Bi,null,$CLJS.Ci,null,$CLJS.Hg,null,$CLJS.yl,null,$CLJS.Di,null],null),
null);return qb.a?qb.a(G):qb(G)}())||($CLJS.oh.j($CLJS.pc(["\n\t",$CLJS.Yh($CLJS.pc([G]))," "])),ip($CLJS.pc([J])));U=$CLJS.K(t);p=null;Y=0}ea=0}else break}Vo(null);l+=1}else{var P=$CLJS.F(g);if(P){p=P;if($CLJS.Gc(p)){var S=$CLJS.Xd(p),W=$CLJS.Yd(p);p=S;var X=$CLJS.ic(S);g=W;f=p;k=X}else{var Z=$CLJS.H(p),ba=null!=Z&&(Z.g&64||$CLJS.Gb===Z.T)?$CLJS.Gd($CLJS.Ui,Z):Z;Y=ba;var ca=$CLJS.N.b(ba,$CLJS.Ai),ia=$CLJS.N.b(ba,$CLJS.Bi),la=$CLJS.N.b(ba,$CLJS.Hg),ma=$CLJS.N.b(ba,$CLJS.yl),va=$CLJS.N.b(ba,$CLJS.Ci),
Ga=$CLJS.N.b(ba,$CLJS.Di);ip($CLJS.pc([la]));$CLJS.oh.j($CLJS.pc([" - failed: "]));$CLJS.q(ma)?$CLJS.oh.j($CLJS.pc([ma])):ip($CLJS.pc([cp(ia)]));$CLJS.Ac(Ga)||$CLJS.oh.j($CLJS.pc([[" in: ",$CLJS.Yh($CLJS.pc([Ga]))].join("")]));$CLJS.Ac(ca)||$CLJS.oh.j($CLJS.pc([[" at: ",$CLJS.Yh($CLJS.pc([ca]))].join("")]));$CLJS.Ac(va)||$CLJS.oh.j($CLJS.pc([[" spec: ",$CLJS.Yh($CLJS.pc([$CLJS.Qh(va)]))].join("")]));var Fa=$CLJS.F(Y);Y=null;for(t=ea=0;;)if(t<ea){var Wa=Y.O(null,t),Oa=$CLJS.uc(Wa,0,null),jc=$CLJS.uc(Wa,
1,null);$CLJS.q(function(){var qb=new $CLJS.Pf(null,new $CLJS.Ka(null,6,[$CLJS.Ai,null,$CLJS.Bi,null,$CLJS.Ci,null,$CLJS.Hg,null,$CLJS.yl,null,$CLJS.Di,null],null),null);return qb.a?qb.a(Oa):qb(Oa)}())||($CLJS.oh.j($CLJS.pc(["\n\t",$CLJS.Yh($CLJS.pc([Oa]))," "])),ip($CLJS.pc([jc])));t+=1}else{var rd=$CLJS.F(Fa);if(rd){var tc=rd;if($CLJS.Gc(tc)){var Jf=$CLJS.Xd(tc),Jb=$CLJS.Yd(tc);tc=Jf;var hh=$CLJS.ic(Jf);Fa=Jb;Y=tc;ea=hh}else{var gf=$CLJS.H(tc),hf=$CLJS.uc(gf,0,null),Kf=$CLJS.uc(gf,1,null);$CLJS.q(function(){var qb=
new $CLJS.Pf(null,new $CLJS.Ka(null,6,[$CLJS.Ai,null,$CLJS.Bi,null,$CLJS.Ci,null,$CLJS.Hg,null,$CLJS.yl,null,$CLJS.Di,null],null),null);return qb.a?qb.a(hf):qb(hf)}())||($CLJS.oh.j($CLJS.pc(["\n\t",$CLJS.Yh($CLJS.pc([hf]))," "])),ip($CLJS.pc([Kf])));Fa=$CLJS.K(tc);Y=null;ea=0}t=0}else break}Vo(null);g=$CLJS.K(p);f=null;k=0}l=0}else break}}finally{$CLJS.Ta=e,$CLJS.Sa=d}return $CLJS.z.a(c)}()]))}$CLJS.og($CLJS.pc(["Success!"]),$CLJS.kg.f($CLJS.Ra(),$CLJS.Ma,!1));return $CLJS.Sa?Vo($CLJS.Ra()):null},
Up=function(a){var b=$CLJS.ri($CLJS.kn,a);if($CLJS.M.b($CLJS.li,b)){b=$CLJS.Ge;var c=$CLJS.gi($CLJS.kn);c=$CLJS.q(c)?new $CLJS.R(null,1,5,$CLJS.T,[c],null):$CLJS.Ge;var d=$CLJS.Ge;b=$CLJS.zi($CLJS.oi.a($CLJS.kn),b,c,d,a);a=$CLJS.q(b)?$CLJS.Ac(b)?null:new $CLJS.Ka(null,3,[$CLJS.Sk,b,$CLJS.Uk,$CLJS.kn,$CLJS.Ak,a],null):null;a=jp.a?jp.a(a):jp(a);a=new $CLJS.Ka(null,2,[$CLJS.Tl,$CLJS.Pl,$CLJS.tn,a],null);a=$CLJS.Xl.a?$CLJS.Xl.a(a):(0,$CLJS.Xl)(a)}else a=new $CLJS.R(null,2,5,$CLJS.T,[$CLJS.kn,b],null);
return $CLJS.ko.a?$CLJS.ko.a(a):(0,$CLJS.ko)(a)},Vp=function(a,b,c){var d=$CLJS.Sf(a);return $CLJS.gg.a(function(){if($CLJS.q($CLJS.M.b?$CLJS.M.b($CLJS.mo,b):$CLJS.M($CLJS.mo,b)))return[d,"_by_props"].join("");if($CLJS.q($CLJS.M.b?$CLJS.M.b($CLJS.oo,b):$CLJS.M($CLJS.oo,b)))return[d,"_by_",$CLJS.z.a(c)].join("");if($CLJS.q($CLJS.M.b?$CLJS.M.b($CLJS.$k,b):$CLJS.M($CLJS.$k,b)))return[d,"_count"].join("");if($CLJS.q($CLJS.M.b?$CLJS.M.b($CLJS.Xo,b):$CLJS.M($CLJS.Xo,b)))return["create_",d].join("");if($CLJS.q($CLJS.M.b?
$CLJS.M.b($CLJS.no,b):$CLJS.M($CLJS.no,b)))return["update_",d].join("");if($CLJS.q($CLJS.M.b?$CLJS.M.b($CLJS.lo,b):$CLJS.M($CLJS.lo,b)))return["delete_",d].join("");throw Error(["No matching clause: ",$CLJS.z.a(b)].join(""));}())},Wp=function(a,b){a=$CLJS.Sf(a);if($CLJS.q($CLJS.M.b?$CLJS.M.b($CLJS.lo,b):$CLJS.M($CLJS.lo,b)))return 0==a.lastIndexOf("delete_",0);if($CLJS.q($CLJS.M.b?$CLJS.M.b($CLJS.mo,b):$CLJS.M($CLJS.mo,b)))return $CLJS.wh(a,"by_props");throw Error(["No matching clause: ",$CLJS.z.a(b)].join(""));
},np=function(a){return $CLJS.Fc($CLJS.H(a))?Up(new $CLJS.Ka(null,1,[$CLJS.Jm,a],null)):Up(new $CLJS.Ka(null,1,[$CLJS.Jm,new $CLJS.R(null,1,5,$CLJS.T,[a],null)],null))},op=function(a){var b=$CLJS.Wh($CLJS.Sf(a),/\./);return $CLJS.M.b($CLJS.ic(b),1)?a:$CLJS.Rc(function(){return function(c,d){return $CLJS.q(c)?$CLJS.fh.b(new $CLJS.R(null,1,5,$CLJS.T,[$CLJS.gg.a(d)],null),new $CLJS.R(null,1,5,$CLJS.T,[c],null)):$CLJS.gg.a(d)}}(b),null,$CLJS.xm(b))},pp=function(a){if($CLJS.Ac(a))return null;$CLJS.$d($CLJS.qo,
a);return"ok"},qp=function(a,b,c){return $CLJS.ie(function(d){var e=$CLJS.uc(d,0,null);d=$CLJS.uc(d,1,null);e=$CLJS.q(c)?[$CLJS.z.a(c),$CLJS.z.a(b),$CLJS.Sf(e)].join(""):$CLJS.Sf(e);return $CLJS.Dc(d)?qp(d,b,e):new $CLJS.R(null,1,5,$CLJS.T,[new $CLJS.R(null,2,5,$CLJS.T,[$CLJS.gg.a(e),d],null)],null)},$CLJS.pc([a]))},rp=function(a){return $CLJS.Ac(a)?a:$CLJS.Fc(a)?Wo(function(b){return $CLJS.gh.b($CLJS.Sd,qp(b,".",null))},a):$CLJS.Dc(a)?$CLJS.gh.b($CLJS.Sd,qp(a,".",null)):a},tp=function(a){return $CLJS.q(a)?
$CLJS.Gd(Yo,$CLJS.Zc(function(b,c,d){return $CLJS.fh.b(b,sp($CLJS.Sd,Wo($CLJS.gg,$CLJS.Wh($CLJS.Sf(c),/\./)),d))},$CLJS.Ge,a)):null},vp=function(a){for(var b=$CLJS.F($CLJS.Co.a(a)),c=null,d=0,e=0;;)if(e<d){var f=c.O(null,e);$CLJS.q($CLJS.Bo.a(f))&&console.error("error:",$CLJS.Bo.a(f));e+=1}else if(b=$CLJS.F(b))c=b,$CLJS.Gc(c)?(b=$CLJS.Xd(c),e=$CLJS.Yd(c),c=b,d=$CLJS.ic(b),b=e):(b=$CLJS.H(c),$CLJS.q($CLJS.Bo.a(b))&&console.error("error:",$CLJS.Bo.a(b)),b=$CLJS.K(c),c=null,d=0),e=0;else break;return console.error(up(a))},
xp=function(a){return function(b){return function(c,d){d=$CLJS.Bh(d)?new $CLJS.Ka(null,2,[$CLJS.xo,d,$CLJS.so,vp],null):d;var e=null!=d&&(d.g&64||$CLJS.Gb===d.T)?$CLJS.Gd($CLJS.Ui,d):d,f=$CLJS.N.b(e,$CLJS.xo),g=$CLJS.N.b(e,$CLJS.so);return $CLJS.q($CLJS.Zb($CLJS.Do))?function(){var k=up($CLJS.kg.j(b,$CLJS.to,c,$CLJS.pc([$CLJS.Ao,a,$CLJS.zo,a]))),l=$CLJS.Zb($CLJS.Do);return l.a?l.a(k):l(k)}().then(function(k,l,m,n){return function(p){var v=gp(p,$CLJS.pc([$CLJS.Sg,!0]));var u=$CLJS.vo.a(v);u=$CLJS.q(u)?
u:$CLJS.Jg.a(v);if($CLJS.M.b(200,u)||$CLJS.Ya(u))return $CLJS.to.a(v);p=new $CLJS.Ka(null,1,[$CLJS.Co,new $CLJS.R(null,1,5,$CLJS.T,[new $CLJS.Ka(null,4,[$CLJS.Bo,"request failed",$CLJS.Jg,p.Od,$CLJS.uo,p.statusText,$CLJS.yo,p.data],null)],null)],null);return n.a?n.a(p):n(p)}}(d,e,f,g,b)).then(function(k,l,m){return function(n){if($CLJS.q($CLJS.to.a(n)))return m.a?m.a(n):m(n);n=new $CLJS.Ka(null,1,[$CLJS.to,n],null);return m.a?m.a(n):m(n)}}(d,e,f,g,b)).catch(function(k,l,m,n){return function(p){p=
new $CLJS.Ka(null,1,[$CLJS.Co,new $CLJS.R(null,1,5,$CLJS.T,[new $CLJS.Ka(null,2,[$CLJS.Bo,"request failed",$CLJS.wo,gp(p,$CLJS.pc([$CLJS.Sg,!1]))],null)],null)],null);return n.a?n.a(p):n(p)}}(d,e,f,g,b)):console.log("not init fetch fn")}}(wp.j($CLJS.pc([$CLJS.Eo,$CLJS.Sd])))},Yp=function(a){if($CLJS.Ac(a))return null;var b=$CLJS.gh.b($CLJS.Sd,$CLJS.he.b(function(d){var e=$CLJS.mp.a(d);d=$CLJS.Hm.a(d);var f=$CLJS.je(function(){return function(g){return $CLJS.M.b($CLJS.lm(g,new $CLJS.R(null,2,5,$CLJS.T,
[$CLJS.Ol,$CLJS.Mj],null)),"OBJECT")||$CLJS.M.b($CLJS.lm(g,new $CLJS.R(null,3,5,$CLJS.T,[$CLJS.Ol,$CLJS.lp,$CLJS.Mj],null)),"OBJECT")||$CLJS.M.b($CLJS.lm(g,new $CLJS.R(null,4,5,$CLJS.T,[$CLJS.Ol,$CLJS.lp,$CLJS.lp,$CLJS.Mj],null)),"OBJECT")}}(e,d),d);d=$CLJS.he.b(function(){return function(g){return $CLJS.kg.f($CLJS.Sd,$CLJS.mp.a(g),function(){var k=$CLJS.lm(g,new $CLJS.R(null,2,5,$CLJS.T,[$CLJS.Ol,$CLJS.mp],null));if($CLJS.q(k))return k;k=$CLJS.lm(g,new $CLJS.R(null,3,5,$CLJS.T,[$CLJS.Ol,$CLJS.lp,
$CLJS.mp],null));return $CLJS.q(k)?k:$CLJS.lm(g,new $CLJS.R(null,4,5,$CLJS.T,[$CLJS.Ol,$CLJS.lp,$CLJS.lp,$CLJS.mp],null))}())}}(e,d,f),f);return $CLJS.$e([e,$CLJS.gh.b($CLJS.Sd,d)])},a));a=$CLJS.gh.b($CLJS.Sd,$CLJS.he.b(function(){return function(d){var e=$CLJS.mp.a(d);d=Wo($CLJS.mp,$CLJS.Hm.a(d));return $CLJS.$e([e,d])}}(b),a));var c=$CLJS.Zc(function(){return function(d,e,f){return $CLJS.wh(e,"_return")?d:$CLJS.kg.f(d,e,f)}}(b,a),null,a);return $CLJS.Zc(function(d,e,f){return function(g,k,l){if($CLJS.Ac($CLJS.N.b(d,
k)))return $CLJS.kg.f(g,$CLJS.gg.a(k),$CLJS.he.b($CLJS.gg,l));l=Wo(function(m,n,p){return function(v){return Xp(k,p,m,null,k,v)}}(d,e,f),l);return $CLJS.kg.f(g,$CLJS.gg.a(k),Wo($CLJS.gg,$CLJS.le(l)))}}(b,a,c),null,c)},Zp=function(a){a=xp(a);var b=function(c,d){return function(e){e=$CLJS.je(function(){return function(f){return $CLJS.M.b($CLJS.Mj.a(f),"OBJECT")&&!$CLJS.Kc(new $CLJS.Pf(null,new $CLJS.Ka(null,2,["QueryRoot",null,"MutationRoot",null],null),null),$CLJS.mp.a(f))}}(c,d),$CLJS.lm(e,new $CLJS.R(null,
3,5,$CLJS.T,[$CLJS.to,$CLJS.hp,$CLJS.kp],null)));e=Yp(e);return $CLJS.$d($CLJS.Hp,e)}}("{ __schema {  queryType { name }  types {  ...FullType }  }}fragment FullType on __Type {  kind  name  description  fields(includeDeprecated: true) {    name    description    args { ...InputValue    }    type { ...TypeRef    }  }}fragment InputValue on __InputValue {  name  description  type {    ...TypeRef  }  defaultValue}fragment TypeRef on __Type {  kind  name  ofType { kind  name    ofType { kind   name   ofType { kind    name   ofType {  kind   name   ofType {  kind     name   ofType {   kind      name  ofType {  kind   name   }  } } } } } }}",
a);a.b?a.b("{ __schema {  queryType { name }  types {  ...FullType }  }}fragment FullType on __Type {  kind  name  description  fields(includeDeprecated: true) {    name    description    args { ...InputValue    }    type { ...TypeRef    }  }}fragment InputValue on __InputValue {  name  description  type {    ...TypeRef  }  defaultValue}fragment TypeRef on __Type {  kind  name  ofType { kind  name    ofType { kind   name   ofType { kind    name   ofType {  kind   name   ofType {  kind     name   ofType {   kind      name  ofType {  kind   name   }  } } } } } }}",
b):a("{ __schema {  queryType { name }  types {  ...FullType }  }}fragment FullType on __Type {  kind  name  description  fields(includeDeprecated: true) {    name    description    args { ...InputValue    }    type { ...TypeRef    }  }}fragment InputValue on __InputValue {  name  description  type {    ...TypeRef  }  defaultValue}fragment TypeRef on __Type {  kind  name  ofType { kind  name    ofType { kind   name   ofType { kind    name   ofType {  kind   name   ofType {  kind     name   ofType {   kind      name  ofType {  kind   name   }  } } } } } }}",
b)},yp=function(a,b,c,d){if($CLJS.q($CLJS.q(c)?d:c)){c=xp(c);$CLJS.q($CLJS.Zb($CLJS.nr))&&Tp($CLJS.pc(["fetch:",d]));var e=function(f,g){return function(k){k=$CLJS.to.a(k);if($CLJS.q($CLJS.q(b)?!$CLJS.Fc(b):b))return k=b.a?b.a(k):b(k),$CLJS.q(a)&&(a.a?a.a(k):a(k)),up(k);if($CLJS.q($CLJS.q(b)?$CLJS.Fc(b):b))return up(Wo(function(l){return function(m){var n=$CLJS.uc(m,0,null);m=$CLJS.uc(m,1,null);n=$CLJS.N.b(l,n);return $CLJS.q($CLJS.q(m)?$CLJS.Bh(m):m)?(m.a?m.a(n):m(n),n):null}}(k,f,g),b));$CLJS.q(a)&&
(a.a?a.a(k):a(k));return up($CLJS.H($CLJS.Nf(k)))}}(d,c);return c.b?c.b(d,e):c(d,e)}return console.log("should set endpoint url before query: ",d)},zp=function(a,b){if($CLJS.q($CLJS.M.b?$CLJS.M.b($CLJS.mo,b):$CLJS.M($CLJS.mo,b))||$CLJS.q($CLJS.M.b?$CLJS.M.b($CLJS.oo,b):$CLJS.M($CLJS.oo,b)))$CLJS.xg.s($CLJS.ro,sp,new $CLJS.R(null,2,5,$CLJS.T,[a,$CLJS.Mo],null),!0);else throw Error(["No matching clause: ",$CLJS.z.a(b)].join(""));},Ap=function(a,b,c){var d=$CLJS.H(b);d=Wp(d,$CLJS.mo);var e=$CLJS.gg.a(function(){var l=
$CLJS.Jo.a(c);return $CLJS.q(l)?l:a}()),f=$CLJS.Zb($CLJS.ro),g=d?$CLJS.lm(f,new $CLJS.R(null,2,5,$CLJS.T,[e,$CLJS.Fo],null)):$CLJS.lm(f,new $CLJS.R(null,2,5,$CLJS.T,[e,$CLJS.Ko],null)),k=d?$CLJS.lm(f,new $CLJS.R(null,2,5,$CLJS.T,[e,$CLJS.Mo],null)):$CLJS.lm(f,new $CLJS.R(null,2,5,$CLJS.T,[e,$CLJS.Lo],null));return $CLJS.M.b(g,b)&&$CLJS.Ya(k)?d?$CLJS.lm(f,new $CLJS.R(null,2,5,$CLJS.T,[e,$CLJS.Io],null)):$CLJS.lm(f,new $CLJS.R(null,2,5,$CLJS.T,[e,$CLJS.oo],null)):null},Bp=function(a,b,c,d){$CLJS.M.b(c,
$CLJS.no)?(a=$CLJS.lm($CLJS.Zb($CLJS.ro),new $CLJS.R(null,2,5,$CLJS.T,[a,b],null)),$CLJS.q(a)&&(d=up(tp(d)),a.a?a.a(d):a(d))):null!=c&&$CLJS.xg.s($CLJS.ro,sp,new $CLJS.R(null,2,5,$CLJS.T,[a,b],null),c)},Dp=function(a,b){var c=$CLJS.lm($CLJS.Zb(a),new $CLJS.R(null,2,5,$CLJS.T,[b,$CLJS.Fo],null)),d=$CLJS.H(c);a=!$CLJS.Ac($CLJS.lm($CLJS.Zb(a),new $CLJS.R(null,2,5,$CLJS.T,[b,$CLJS.Io],null)));return $CLJS.q(a?c:a)?(zp(b,$CLJS.mo),yp($o(Cp,b,c),d,$CLJS.Zb($CLJS.qo),np(c))):null},Ep=function(a,b,c){$CLJS.Ac(b)?
Dp($CLJS.ro,a):(b=$CLJS.im(b)?$CLJS.um($CLJS.he.b($CLJS.gg,b)):$CLJS.um(new $CLJS.R(null,1,5,$CLJS.T,[$CLJS.gg.a(b)],null)),Wo(function(d,e){return function(f){return Dp(e,f)}}(b,$CLJS.ro),$CLJS.fh.b(b,a)),Wo(function(d,e){return function(f){var g=$CLJS.lm($CLJS.Zb(e),new $CLJS.R(null,2,5,$CLJS.T,[f,$CLJS.Ko],null)),k=$CLJS.H(g),l=!$CLJS.Ac($CLJS.lm($CLJS.Zb(e),new $CLJS.R(null,2,5,$CLJS.T,[f,$CLJS.oo],null)));$CLJS.q(l?g:l)?(zp(f,$CLJS.oo),f=yp($o(Cp,f,g),k,$CLJS.Zb($CLJS.qo),np(g))):f=null;return f}}(b,
$CLJS.ro),b));return c},Fp=function(a,b,c){a=$CLJS.q($CLJS.jq.a(c))?null:Ap(a,b,c);return new $CLJS.Ka(null,3,[$CLJS.Rg,np(b),$CLJS.Oo,a,$CLJS.No,b],null)},Gp=function(a,b,c,d){b=wp.j($CLJS.pc([b,c]));c=$CLJS.Sf(a);d=Wp(a,$CLJS.lo)?new $CLJS.R(null,1,5,$CLJS.T,[new $CLJS.R(null,2,5,$CLJS.T,[a,b],null)],null):$CLJS.Ac(d)?new $CLJS.R(null,1,5,$CLJS.T,[new $CLJS.R(null,3,5,$CLJS.T,[a,b,new $CLJS.R(null,1,5,$CLJS.T,[$CLJS.po],null)],null)],null):new $CLJS.R(null,1,5,$CLJS.T,[new $CLJS.R(null,3,5,$CLJS.T,
[a,b,d],null)],null);d=Up(new $CLJS.Ka(null,2,[$CLJS.Yn,new $CLJS.Ka(null,2,[$CLJS.xn,$CLJS.mn,$CLJS.Fn,c],null),$CLJS.Jm,d],null));return new $CLJS.Ka(null,2,[$CLJS.mn,d,$CLJS.No,new $CLJS.R(null,2,5,$CLJS.T,[a,b],null)],null)},$p=function(a){return $CLJS.N.b($CLJS.Zb($CLJS.Hp),a)},aq=function(a,b,c,d){if($CLJS.Ac(b))return null;var e=$CLJS.H($CLJS.Lf(b));e=Vp(a,$CLJS.oo,$CLJS.Sf(e));c=Wo(op,$CLJS.Ac(c)?$p(a):c);return Fp(a,new $CLJS.R(null,3,5,$CLJS.T,[e,b,c],null),d)},bq=function(a,b,c,d){var e=
Vp(a,$CLJS.mo,"id");c=Wo(op,$CLJS.Ac(c)?$p(a):c);var f=Sp(b);b=$CLJS.Ac(b)?new $CLJS.R(null,2,5,$CLJS.T,[e,c],null):new $CLJS.R(null,3,5,$CLJS.T,[e,f,c],null);return Fp(a,b,d)},cq=function(a,b,c){return function(d){var e=$CLJS.gg.a(function(){var g=$CLJS.Jo.a(b);return $CLJS.q(g)?g:a}()),f=$CLJS.Po.a(b);Cp.s(e,c,rp(d),f);return $CLJS.q(f)?(d=up(d),f.a?f.a(d):f(d)):null}},dq=function(a,b,c,d){var e=$CLJS.H(b);a=cq(a,d,b);$CLJS.q($CLJS.Zb($CLJS.nr))&&console.log("fetch:",c);return yp(a,e,$CLJS.Zb($CLJS.qo),
c)},eq=function(a){var b=Wo(function(c){var d=null!=c&&(c.g&64||$CLJS.Gb===c.T)?$CLJS.Gd($CLJS.Ui,c):c;c=$CLJS.N.b(d,$CLJS.Np);var e=$CLJS.N.b(d,$CLJS.Qp);d=$CLJS.N.b(d,$CLJS.No);return new $CLJS.R(null,2,5,$CLJS.T,[$CLJS.H(d),cq(c,e,d)],null)},a);a=np(Wo($CLJS.No,a));return yp(null,b,$CLJS.Zb($CLJS.qo),a)},Ip=function(a,b,c,d,e){if($CLJS.Ac(d))return dq(a,b,c,e);a=$CLJS.Po.a(e);d=up(d);$CLJS.q(a)&&(a.a?a.a(d):a(d));return new Promise(function(f,g){return function(k){return k.a?k.a(g):k(g)}}(a,d))},
fq=function(a,b,c,d){b=bq(a,b,c,d);var e=null!=b&&(b.g&64||$CLJS.Gb===b.T)?$CLJS.Gd($CLJS.Ui,b):b;b=$CLJS.N.b(e,$CLJS.Rg);c=$CLJS.N.b(e,$CLJS.Oo);e=$CLJS.N.b(e,$CLJS.No);return Ip(a,e,b,Wo(tp,c),d)},gq=function(a){if($CLJS.Fc($CLJS.H(a))){var b=Wo(function(e){var f=$CLJS.uc(e,0,null),g=$CLJS.uc(e,1,null),k=$CLJS.uc(e,2,null);e=$CLJS.uc(e,3,null);f=$CLJS.gg.a(f);k=$CLJS.he.b($CLJS.gg,k);g=$CLJS.q($CLJS.oo.a(e))?aq(f,g,k,e):bq(f,g,k,e);return $CLJS.kg.j(g,$CLJS.Np,f,$CLJS.pc([$CLJS.Qp,e]))},a),c=Wo($CLJS.Oo,
b);return $CLJS.q($CLJS.Fh($CLJS.Ac,c))?eq(b):new Promise(function(e,f){return function(g){var k=up(Wo(function(){return function(l){return Wo(tp,l)}}(e,f),f));return g.a?g.a(k):g(k)}}(b,c))}b=$CLJS.uc(a,0,null);c=$CLJS.uc(a,1,null);var d=$CLJS.uc(a,2,null);a=$CLJS.uc(a,3,null);return fq(b,c,d,a)},hq=function(a,b){var c=Vp(a,$CLJS.$k,"id"),d=$CLJS.Ac(b)?new $CLJS.R(null,1,5,$CLJS.T,[c],null):new $CLJS.R(null,2,5,$CLJS.T,[c,b],null),e=Vp(a,$CLJS.mo,"id"),f=Wo(op,$p(a));b=$CLJS.Ac(b)?new $CLJS.R(null,
2,5,$CLJS.T,[e,f],null):new $CLJS.R(null,3,5,$CLJS.T,[e,b,f],null);a=Ap(a,b,null);return $CLJS.Ac(a)?yp(null,c,$CLJS.Zb($CLJS.qo),np(d)):new Promise(function(g,k,l,m,n,p){return function(v){var u=$CLJS.ic(p);return v.a?v.a(u):v(u)}}(c,d,e,f,b,a))},Jp=function Jp(a){if(null!=a&&null!=a.Jc)return a.Jc(a);var c=Jp[$CLJS.Ca(null==a?null:a)];if(null!=c)return c.a?c.a(a):c(a);c=Jp._;if(null!=c)return c.a?c.a(a):c(a);throw $CLJS.ab("IEncodeJS.-clj-\x3ejs",a);},ep=function ep(a,b){if(null!=a&&null!=a.Hc)return a.Hc(a,
b);var d=ep[$CLJS.Ca(null==a?null:a)];if(null!=d)return d.b?d.b(a,b):d(a,b);d=ep._;if(null!=d)return d.b?d.b(a,b):d(a,b);throw $CLJS.ab("IEncodeClojure.-js-\x3eclj",a);},fp=function fp(a){for(var c=[],d=arguments.length,e=0;;)if(e<d)c.push(arguments[e]),e+=1;else break;return fp.j(0<c.length?new $CLJS.Nb(c.slice(0),0,null):null)};fp.j=function(a){a=a instanceof $CLJS.Nb&&0===a.m?a.c:Pp(a);return $CLJS.$e(a)};fp.A=0;fp.C=function(a){return this.j($CLJS.F(a))};
var sp=function sp(a,b,c){b=$CLJS.F(b);var e=$CLJS.H(b),f=$CLJS.K(b);return f?$CLJS.kg.f(a,e,function(){var g=$CLJS.N.b(a,e);return sp.f?sp.f(g,f,c):sp(g,f,c)}()):$CLJS.kg.f(a,e,c)},wp=function wp(a){for(var c=[],d=arguments.length,e=0;;)if(e<d)c.push(arguments[e]),e+=1;else break;return wp.j(0<c.length?new $CLJS.Nb(c.slice(0),0,null):null)};wp.j=function(a){return $CLJS.q($CLJS.Fh($CLJS.$c,a))?$CLJS.Wc(function(b,c){return $CLJS.fh.b($CLJS.q(b)?b:$CLJS.Sd,c)},a):null};wp.A=0;wp.C=function(a){return this.j($CLJS.F(a))};
var bp=function bp(a,b){return ap($CLJS.qm(bp,a),a,b)},up=function up(a){for(var c=[],d=arguments.length,e=0;;)if(e<d)c.push(arguments[e]),e+=1;else break;return up.j(arguments[0],1<c.length?new $CLJS.Nb(c.slice(1),0,null):null)};
up.j=function(a,b){var c=null!=b&&(b.g&64||$CLJS.Gb===b.T)?$CLJS.Gd($CLJS.Ui,b):b,d=$CLJS.N.f(c,$CLJS.Ng,$CLJS.Sf),e=function(){return function(g){var k=f;return(null!=g?$CLJS.Gb===g.Ic||(g.ic?0:$CLJS.Za(Qo,g)):$CLJS.Za(Qo,g))?Jp(g):"string"===typeof g||"number"===typeof g||g instanceof $CLJS.Q||g instanceof $CLJS.C?k.a?k.a(g):k(g):$CLJS.Yh($CLJS.pc([g]))}}(b,c,c,d),f=function(g,k,l,m){return function v(p){if(null==p)return null;if(null!=p?$CLJS.Gb===p.Ic||(p.ic?0:$CLJS.Za(Qo,p)):$CLJS.Za(Qo,p))return Jp(p);
if(p instanceof $CLJS.Q)return m.a?m.a(p):m(p);if(p instanceof $CLJS.C)return $CLJS.z.a(p);if($CLJS.Dc(p)){var u={};p=$CLJS.F(p);for(var x=null,D=0,I=0;;)if(I<D){var O=x.O(null,I),U=$CLJS.uc(O,0,null),Y=$CLJS.uc(O,1,null);O=u;U=e(U);Y=v(Y);O[U]=Y;I+=1}else if(p=$CLJS.F(p))$CLJS.Gc(p)?(D=$CLJS.Xd(p),p=$CLJS.Yd(p),x=D,D=$CLJS.ic(D)):(x=$CLJS.H(p),D=$CLJS.uc(x,0,null),I=$CLJS.uc(x,1,null),x=u,D=e(D),I=v(I),x[D]=I,p=$CLJS.K(p),x=null,D=0),I=0;else break;return u}if($CLJS.im(p)){u=[];p=$CLJS.F($CLJS.he.b(v,
p));x=null;for(I=D=0;;)if(I<D)O=x.O(null,I),u.push(O),I+=1;else if(p=$CLJS.F(p))x=p,$CLJS.Gc(x)?(p=$CLJS.Xd(x),I=$CLJS.Yd(x),x=p,D=$CLJS.ic(p),p=I):(p=$CLJS.H(x),u.push(p),p=$CLJS.K(x),x=null,D=0),I=0;else break;return u}return p}}(b,c,c,d);return f(a)};up.A=1;up.C=function(a){var b=$CLJS.H(a);a=$CLJS.K(a);return this.j(b,a)};var Yo=function Yo(a){for(var c=[],d=arguments.length,e=0;;)if(e<d)c.push(arguments[e]),e+=1;else break;return Yo.j(arguments[0],1<c.length?new $CLJS.Nb(c.slice(1),0,null):null)};
Yo.j=function(a,b){return $CLJS.q($CLJS.Fh($CLJS.$c,b))?$CLJS.Rc(function(c,d){return $CLJS.Dc(c)&&$CLJS.Dc(d)?Zo($CLJS.pc([c,d])):d},a,b):a};Yo.A=1;Yo.C=function(a){var b=$CLJS.H(a);a=$CLJS.K(a);return this.j(b,a)};
var Xp=function Xp(a,b,c,d,e,f){e=$CLJS.lm(c,new $CLJS.R(null,2,5,$CLJS.T,[e,f],null));return $CLJS.q($CLJS.q(e)?!$CLJS.M.b(a,e)&&$CLJS.Ya($CLJS.q(d)?-1!=d.indexOf(e):d):e)?$CLJS.he.b(function(k){return function(l){var m=[$CLJS.z.a(d),$CLJS.z.a(f),"."].join("");return Xp.S?Xp.S(a,b,c,m,k,l):Xp(a,b,c,m,k,l)}}(e),$CLJS.N.b(b,e)):[$CLJS.z.a(d),$CLJS.z.a(f)].join("")},Cp=function Cp(a){switch(arguments.length){case 4:return Cp.s(arguments[0],arguments[1],arguments[2],arguments[3]);case 3:return Cp.f(arguments[0],
arguments[1],arguments[2]);default:throw Error(["Invalid arity: ",$CLJS.z.a(arguments.length)].join(""));}};
Cp.s=function(a,b,c,d){if($CLJS.Fc(c))$CLJS.xg.s($CLJS.ro,sp,new $CLJS.R(null,2,5,$CLJS.T,[a,$CLJS.Io],null),c),$CLJS.xg.s($CLJS.ro,sp,new $CLJS.R(null,2,5,$CLJS.T,[a,$CLJS.Fo],null),b),$CLJS.xg.s($CLJS.ro,sp,new $CLJS.R(null,2,5,$CLJS.T,[a,$CLJS.Mo],null),!1),Bp(a,$CLJS.Go,d,c);else{var e=wp.j($CLJS.pc([$CLJS.lm($CLJS.Zb($CLJS.ro),new $CLJS.R(null,2,5,$CLJS.T,[a,$CLJS.oo],null)),c]));$CLJS.xg.s($CLJS.ro,sp,new $CLJS.R(null,2,5,$CLJS.T,[a,$CLJS.oo],null),e);$CLJS.xg.s($CLJS.ro,sp,new $CLJS.R(null,
2,5,$CLJS.T,[a,$CLJS.Ko],null),b);$CLJS.xg.s($CLJS.ro,sp,new $CLJS.R(null,2,5,$CLJS.T,[a,$CLJS.Lo],null),!1);Bp(a,$CLJS.Ho,d,c)}return c};Cp.f=function(a,b,c){return Cp.s(a,b,c,$CLJS.no)};Cp.A=4;var kI=new $CLJS.Q(null,"enable_log","enable_log",-1994769367),iq=new $CLJS.Q(null,"init_schema","init_schema",-879641052);module.exports={find_one:function(a,b,c,d){if($CLJS.q($CLJS.q(a)?b:a)){a=$CLJS.gg.a(a);b=gp(b,$CLJS.pc([$CLJS.Sg,!0]));c=Wo($CLJS.gg,c);d=gp(d,$CLJS.pc([$CLJS.Sg,!0]));c=aq(a,b,c,d);var e=null!=c&&(c.g&64||$CLJS.Gb===c.T)?$CLJS.Gd($CLJS.Ui,c):c;c=$CLJS.N.b(e,$CLJS.Rg);b=$CLJS.N.b(e,$CLJS.Oo);e=$CLJS.N.b(e,$CLJS.No);return Ip(a,e,c,tp(b),d)}return null},find:function(a){return $CLJS.q(a)?gq(gp(a,$CLJS.pc([$CLJS.Sg,!0]))):null},remove:function(a,b,c){if($CLJS.q(a)){a=$CLJS.gg.a(a);b=gp(b,$CLJS.pc([$CLJS.Sg,
!0]));c=gp(c,$CLJS.pc([$CLJS.Sg,!0]));var d=Vp(a,$CLJS.lo,"id");b=Gp(d,b,null,null);b=null!=b&&(b.g&64||$CLJS.Gb===b.T)?$CLJS.Gd($CLJS.Ui,b):b;b=$CLJS.N.b(b,$CLJS.mn);a=yp($o(Ep,a,$CLJS.Jo.a(c)),null,$CLJS.Zb($CLJS.qo),b)}else a=null;return a},insert:function(a,b,c,d){if($CLJS.q($CLJS.q(a)?b:a)){a=$CLJS.gg.a(a);b=gp(b,$CLJS.pc([$CLJS.Sg,!0]));c=$CLJS.q(c)?Wo($CLJS.gg,c):null;d=gp(d,$CLJS.pc([$CLJS.Sg,!0]));var e=Vp(a,$CLJS.Xo,"id");b=Gp(e,b,null,c);b=null!=b&&(b.g&64||$CLJS.Gb===b.T)?$CLJS.Gd($CLJS.Ui,
b):b;b=$CLJS.N.b(b,$CLJS.mn);a=yp($o(Ep,a,$CLJS.Jo.a(d)),null,$CLJS.Zb($CLJS.qo),b)}else a=null;return a},find_many:function(a,b,c,d){return $CLJS.q(a)?fq($CLJS.gg.a(a),gp(b,$CLJS.pc([$CLJS.Sg,!0])),Wo($CLJS.gg,c),gp(d,$CLJS.pc([$CLJS.Sg,!0]))):null},init:function(a,b,c){$CLJS.q(b)&&$CLJS.$d($CLJS.Do,b);return $CLJS.q(a)?(b=gp(c,$CLJS.pc([$CLJS.Sg,!0])),c=$CLJS.Dc(b)?new $CLJS.R(null,2,5,$CLJS.T,[iq.a(b),kI.a(b)],null):new $CLJS.R(null,2,5,$CLJS.T,[b,!1],null),b=$CLJS.uc(c,0,null),c=$CLJS.uc(c,1,
null),$CLJS.q(b)&&Zp(a),$CLJS.$d($CLJS.nr,c),pp(a)):null},hello:function(a){return["Hi devtools installed, ",$CLJS.z.a(a),"!"].join("")},update:function(a,b,c,d,e){if($CLJS.q($CLJS.q(a)?b:a)){a=$CLJS.gg.a(a);b=gp(b,$CLJS.pc([$CLJS.Sg,!0]));c=gp(c,$CLJS.pc([$CLJS.Sg,!0]));d=$CLJS.q(d)?Wo($CLJS.gg,d):null;e=gp(e,$CLJS.pc([$CLJS.Sg,!0]));var f=Vp(a,$CLJS.no,"id");b=Gp(f,b,c,d);b=null!=b&&(b.g&64||$CLJS.Gb===b.T)?$CLJS.Gd($CLJS.Ui,b):b;b=$CLJS.N.b(b,$CLJS.mn);a=yp($o(Ep,a,$CLJS.Jo.a(e)),null,$CLJS.Zb($CLJS.qo),
b)}else a=null;return a},set_endpoint_url:function(a){return pp(a)},count:function(a,b){return $CLJS.q(a)?hq($CLJS.gg.a(a),gp(b,$CLJS.pc([$CLJS.Sg,!0]))):null}};