var window=global;var $CLJS=require("./cljs_env");require("./goog.base.js");require("./cljs.core.js");require("./graphql_cache.query.tools.js");require("./graphql_cache.query.interface.js");require("./graphql_cache.query.fetch_data.js");
var Qo=function(){},Ro=function(){},So=function(a){a:for(var b=a;;)if(b=$CLJS.F(b))b=$CLJS.K(b);else break a;return a},To=function(a,b){return $CLJS.Lh(function(c,d){c=a.a?a.a(c):a(c);d=a.a?a.a(d):a(d);var e=$CLJS.Kh($CLJS.Mc);return e.b?e.b(c,d):e(c,d)},b)},Uo=function(a,b){return To(a,b)},Vo=function(a){$CLJS.ag("\n");return $CLJS.N.b(a,$CLJS.La),null},Wo=function(a,b){return $CLJS.xe($CLJS.Rc(function(c,d){return $CLJS.we.b(c,a.a?a.a(d):a(d))},$CLJS.Fe($CLJS.Ge),b))},Pp=function(a){function b(d,
e){d.push(e);return d}var c=[];return $CLJS.Rc?$CLJS.Rc(b,c,a):$CLJS.Sc(b,c,a)},Zo=function(a){var b=Yo;return $CLJS.q($CLJS.Fh($CLJS.$c,a))?$CLJS.Wc(function(c){return function(d,e){return $CLJS.Rc(c,$CLJS.q(d)?d:$CLJS.Sd,$CLJS.F(e))}}(function(c,d){var e=$CLJS.Be(d),f=$CLJS.De(d);return $CLJS.Kc(c,e)?$CLJS.kg.f(c,e,function(){var g=$CLJS.N.b(c,e);return b.b?b.b(g,f):b(g,f)}()):$CLJS.kg.f(c,e,f)}),a):null},$o=function(a,b,c){return function(){function d(m,n,p){return a.I?a.I(b,c,m,n,p):a(b,c,m,n,
p)}function e(m,n){return a.s?a.s(b,c,m,n):a(b,c,m,n)}function f(m){return a.f?a.f(b,c,m):a(b,c,m)}function g(){return a.b?a.b(b,c):a(b,c)}var k=null,l=function(){function m(p,v,u,x){var D=null;if(3<arguments.length){D=0;for(var I=Array(arguments.length-3);D<I.length;)I[D]=arguments[D+3],++D;D=new $CLJS.Nb(I,0,null)}return n.call(this,p,v,u,D)}function n(p,v,u,x){return $CLJS.Kd(a,b,c,p,v,$CLJS.pc([u,x]))}m.A=3;m.C=function(p){var v=$CLJS.H(p);p=$CLJS.K(p);var u=$CLJS.H(p);p=$CLJS.K(p);var x=$CLJS.H(p);
p=$CLJS.Rb(p);return n(v,u,x,p)};m.j=n;return m}();k=function(m,n,p,v){switch(arguments.length){case 0:return g.call(this);case 1:return f.call(this,m);case 2:return e.call(this,m,n);case 3:return d.call(this,m,n,p);default:var u=null;if(3<arguments.length){u=0;for(var x=Array(arguments.length-3);u<x.length;)x[u]=arguments[u+3],++u;u=new $CLJS.Nb(x,0,null)}return l.j(m,n,p,u)}throw Error("Invalid arity: "+arguments.length);};k.A=3;k.C=l.C;k.u=g;k.a=f;k.b=e;k.f=d;k.j=l.j;return k}()},ap=function(a,
b,c){if($CLJS.gd(c)){var d=$CLJS.Gd($CLJS.V,$CLJS.he.b(a,c));return b.a?b.a(d):b(d)}return $CLJS.ze(c)?(d=new $CLJS.Xe(function(){var e=$CLJS.Be(c);return a.a?a.a(e):a(e)}(),function(){var e=$CLJS.De(c);return a.a?a.a(e):a(e)}()),b.a?b.a(d):b(d)):$CLJS.Ch(c)?(d=So($CLJS.he.b(a,c)),b.a?b.a(d):b(d)):$CLJS.Ec(c)?(d=$CLJS.Rc(function(e,f){return $CLJS.fh.b(e,a.a?a.a(f):a(f))},c,c),b.a?b.a(d):b(d)):$CLJS.im(c)?(d=$CLJS.gh.b($CLJS.hm(c),$CLJS.he.b(a,c)),b.a?b.a(d):b(d)):b.a?b.a(c):b(c)},cp=function(a){return $CLJS.Ch(a)?
bp(function(b){var c=(c=b instanceof $CLJS.C)?$CLJS.md(b):c;return $CLJS.q(c)?$CLJS.ch.a($CLJS.Sf(b)):$CLJS.Ch(b)&&$CLJS.M.b($CLJS.Mg,$CLJS.H(b))&&$CLJS.M.b(new $CLJS.R(null,1,5,$CLJS.T,[$CLJS.ul],null),$CLJS.rc(b))?$CLJS.Qh(b):b},a):$CLJS.q(function(){var b=a instanceof $CLJS.C;return b?$CLJS.md(a):b}())?$CLJS.ch.a($CLJS.Sf(a)):a},gp=function(a,b){var c=null!=b&&(b.g&64||$CLJS.Gb===b.T)?$CLJS.Gd($CLJS.Ui,b):b,d=$CLJS.N.b(c,$CLJS.Sg);return function(e,f,g,k){return function n(m){return(null!=m?$CLJS.Gb===
m.Cd||(m.ic?0:$CLJS.Za(Ro,m)):$CLJS.Za(Ro,m))?ep(m,$CLJS.Gd(fp,b)):$CLJS.Ch(m)?So($CLJS.he.b(n,m)):$CLJS.ze(m)?new $CLJS.Xe(n($CLJS.Be(m)),n($CLJS.De(m))):$CLJS.im(m)?$CLJS.gh.f($CLJS.hm(m),$CLJS.he.a(n),m):$CLJS.Xa(m)?$CLJS.xe($CLJS.Rc(function(){return function(p,v){return $CLJS.we.b(p,n(v))}}(e,f,g,k),$CLJS.Fe($CLJS.Ge),m)):$CLJS.$a(m)===Object?$CLJS.xe($CLJS.Rc(function(p,v,u,x){return function(D,I){return $CLJS.zd(D,x.a?x.a(I):x(I),n(null!==m&&I in m?m[I]:void 0))}}(e,f,g,k),$CLJS.Fe($CLJS.Sd),
$CLJS.Ea(m))):m}}(b,c,d,$CLJS.q(d)?$CLJS.gg:$CLJS.z)(a)},ip=function(a){$CLJS.og(a,$CLJS.Ra())},jp=function(a){if($CLJS.q(a)){var b=Uo(function(c){return-$CLJS.ic($CLJS.Ai.a(c))},Uo(function(c){return-$CLJS.ic($CLJS.Di.a(c))},$CLJS.Sk.a(a)));return $CLJS.oh.j($CLJS.pc([function(){var c=new $CLJS.Ja,d=$CLJS.Sa,e=$CLJS.Ta,f=function(qb,jf,pi,ih){return function(Oj){return ih.append(Oj)}}(d,e,!0,c,b);$CLJS.Sa=!0;$CLJS.Ta=f;try{var g=$CLJS.F(b);f=null;for(var k=0,l=0;;)if(l<k){var m=f.O(null,l),n=null!=
m&&(m.g&64||$CLJS.Gb===m.T)?$CLJS.Gd($CLJS.Ui,m):m,p=n,v=$CLJS.N.b(n,$CLJS.Ai),u=$CLJS.N.b(n,$CLJS.Bi),x=$CLJS.N.b(n,$CLJS.Hg),D=$CLJS.N.b(n,$CLJS.yl),I=$CLJS.N.b(n,$CLJS.Ci),O=$CLJS.N.b(n,$CLJS.Di);ip($CLJS.pc([x]));$CLJS.oh.j($CLJS.pc([" - failed: "]));$CLJS.q(D)?$CLJS.oh.j($CLJS.pc([D])):ip($CLJS.pc([cp(u)]));$CLJS.Ac(O)||$CLJS.oh.j($CLJS.pc([[" in: ",$CLJS.Yh($CLJS.pc([O]))].join("")]));$CLJS.Ac(v)||$CLJS.oh.j($CLJS.pc([[" at: ",$CLJS.Yh($CLJS.pc([v]))].join("")]));$CLJS.Ac(I)||$CLJS.oh.j($CLJS.pc([[" spec: ",
$CLJS.Yh($CLJS.pc([$CLJS.Qh(I)]))].join("")]));var U=$CLJS.F(p);p=null;for(var Y=0,ea=0;;)if(ea<Y){var na=p.O(null,ea),da=$CLJS.uc(na,0,null),r=$CLJS.uc(na,1,null);$CLJS.q(function(){var qb=new $CLJS.Pf(null,new $CLJS.Ka(null,6,[$CLJS.Ai,null,$CLJS.Bi,null,$CLJS.Ci,null,$CLJS.Hg,null,$CLJS.yl,null,$CLJS.Di,null],null),null);return qb.a?qb.a(da):qb(da)}())||($CLJS.oh.j($CLJS.pc(["\n\t",$CLJS.Yh($CLJS.pc([da]))," "])),ip($CLJS.pc([r])));ea+=1}else{var w=$CLJS.F(U);if(w){var t=w;if($CLJS.Gc(t)){var y=
$CLJS.Xd(t),A=$CLJS.Yd(t);t=y;var B=$CLJS.ic(y);U=A;p=t;Y=B}else{var E=$CLJS.H(t),G=$CLJS.uc(E,0,null),J=$CLJS.uc(E,1,null);$CLJS.q(function(){var qb=new $CLJS.Pf(null,new $CLJS.Ka(null,6,[$CLJS.Ai,null,$CLJS.Bi,null,$CLJS.Ci,null,$CLJS.Hg,null,$CLJS.yl,null,$CLJS.Di,null],null),null);return qb.a?qb.a(G):qb(G)}())||($CLJS.oh.j($CLJS.pc(["\n\t",$CLJS.Yh($CLJS.pc([G]))," "])),ip($CLJS.pc([J])));U=$CLJS.K(t);p=null;Y=0}ea=0}else break}Vo(null);l+=1}else{var P=$CLJS.F(g);if(P){p=P;if($CLJS.Gc(p)){var S=
$CLJS.Xd(p),W=$CLJS.Yd(p);p=S;var X=$CLJS.ic(S);g=W;f=p;k=X}else{var Z=$CLJS.H(p),ba=null!=Z&&(Z.g&64||$CLJS.Gb===Z.T)?$CLJS.Gd($CLJS.Ui,Z):Z;Y=ba;var ca=$CLJS.N.b(ba,$CLJS.Ai),ia=$CLJS.N.b(ba,$CLJS.Bi),la=$CLJS.N.b(ba,$CLJS.Hg),ma=$CLJS.N.b(ba,$CLJS.yl),va=$CLJS.N.b(ba,$CLJS.Ci),Ga=$CLJS.N.b(ba,$CLJS.Di);ip($CLJS.pc([la]));$CLJS.oh.j($CLJS.pc([" - failed: "]));$CLJS.q(ma)?$CLJS.oh.j($CLJS.pc([ma])):ip($CLJS.pc([cp(ia)]));$CLJS.Ac(Ga)||$CLJS.oh.j($CLJS.pc([[" in: ",$CLJS.Yh($CLJS.pc([Ga]))].join("")]));
$CLJS.Ac(ca)||$CLJS.oh.j($CLJS.pc([[" at: ",$CLJS.Yh($CLJS.pc([ca]))].join("")]));$CLJS.Ac(va)||$CLJS.oh.j($CLJS.pc([[" spec: ",$CLJS.Yh($CLJS.pc([$CLJS.Qh(va)]))].join("")]));var Fa=$CLJS.F(Y);Y=null;for(t=ea=0;;)if(t<ea){var Wa=Y.O(null,t),Oa=$CLJS.uc(Wa,0,null),jc=$CLJS.uc(Wa,1,null);$CLJS.q(function(){var qb=new $CLJS.Pf(null,new $CLJS.Ka(null,6,[$CLJS.Ai,null,$CLJS.Bi,null,$CLJS.Ci,null,$CLJS.Hg,null,$CLJS.yl,null,$CLJS.Di,null],null),null);return qb.a?qb.a(Oa):qb(Oa)}())||($CLJS.oh.j($CLJS.pc(["\n\t",
$CLJS.Yh($CLJS.pc([Oa]))," "])),ip($CLJS.pc([jc])));t+=1}else{var rd=$CLJS.F(Fa);if(rd){var tc=rd;if($CLJS.Gc(tc)){var Jf=$CLJS.Xd(tc),Jb=$CLJS.Yd(tc);tc=Jf;var hh=$CLJS.ic(Jf);Fa=Jb;Y=tc;ea=hh}else{var gf=$CLJS.H(tc),hf=$CLJS.uc(gf,0,null),Kf=$CLJS.uc(gf,1,null);$CLJS.q(function(){var qb=new $CLJS.Pf(null,new $CLJS.Ka(null,6,[$CLJS.Ai,null,$CLJS.Bi,null,$CLJS.Ci,null,$CLJS.Hg,null,$CLJS.yl,null,$CLJS.Di,null],null),null);return qb.a?qb.a(hf):qb(hf)}())||($CLJS.oh.j($CLJS.pc(["\n\t",$CLJS.Yh($CLJS.pc([hf])),
" "])),ip($CLJS.pc([Kf])));Fa=$CLJS.K(tc);Y=null;ea=0}t=0}else break}Vo(null);g=$CLJS.K(p);f=null;k=0}l=0}else break}}finally{$CLJS.Ta=e,$CLJS.Sa=d}return $CLJS.z.a(c)}()]))}$CLJS.og($CLJS.pc(["Success!"]),$CLJS.kg.f($CLJS.Ra(),$CLJS.Ma,!1));return $CLJS.Sa?Vo($CLJS.Ra()):null},Sp=function(a){for(var b=[],c=arguments.length,d=0;;)if(d<c)b.push(arguments[d]),d+=1;else break;a:{c=arguments[0];b=$CLJS.uc(1<b.length?new $CLJS.Nb(b.slice(1),0,null):null,0,null);b=null!=b&&(b.g&64||$CLJS.Gb===b.T)?$CLJS.Gd($CLJS.Ui,
b):b;d=$CLJS.N.b(b,$CLJS.Np);b=$CLJS.ko;$CLJS.ko=$CLJS.q(d)?d:$CLJS.ko;try{var e=$CLJS.ri($CLJS.go,c);if($CLJS.M.b($CLJS.li,e)){e=$CLJS.Ge;var f=$CLJS.gi($CLJS.go),g=$CLJS.q(f)?new $CLJS.R(null,1,5,$CLJS.T,[f],null):$CLJS.Ge;f=$CLJS.Ge;var k=$CLJS.zi($CLJS.oi.a($CLJS.go),e,g,f,c);var l=$CLJS.q(k)?$CLJS.Ac(k)?null:new $CLJS.Ka(null,3,[$CLJS.Sk,k,$CLJS.Uk,$CLJS.go,$CLJS.Ak,c],null):null;var m=jp.a?jp.a(l):jp(l);var n=new $CLJS.Ka(null,2,[$CLJS.Pl,$CLJS.Tl,$CLJS.Sn,m],null);var p=$CLJS.Xl.a?$CLJS.Xl.a(n):
(0,$CLJS.Xl)(n)}else p=new $CLJS.R(null,2,5,$CLJS.T,[$CLJS.go,e],null);var v=$CLJS.Rp.a?$CLJS.Rp.a(p):(0,$CLJS.Rp)(p);break a}finally{$CLJS.ko=b}v=void 0}return v},np=function(a){return $CLJS.Fc($CLJS.H(a))?Sp(new $CLJS.Ka(null,1,[$CLJS.Im,a],null)):Sp(new $CLJS.Ka(null,1,[$CLJS.Im,new $CLJS.R(null,1,5,$CLJS.T,[a],null)],null))},op=function(a){var b=$CLJS.Wh($CLJS.Sf(a),/\./);return $CLJS.M.b($CLJS.ic(b),1)?a:$CLJS.Rc(function(){return function(c,d){return $CLJS.q(c)?$CLJS.fh.b(new $CLJS.R(null,1,
5,$CLJS.T,[$CLJS.gg.a(d)],null),c):new $CLJS.R(null,1,5,$CLJS.T,[$CLJS.gg.a(d)],null)}}(b),null,$CLJS.xm(b))},pp=function(a){if($CLJS.Ac(a))return null;$CLJS.$d($CLJS.qo,a);return"ok"},qp=function(a,b,c){return $CLJS.ie(function(d){var e=$CLJS.uc(d,0,null);d=$CLJS.uc(d,1,null);e=$CLJS.q(c)?[$CLJS.z.a(c),$CLJS.z.a(b),$CLJS.Sf(e)].join(""):$CLJS.Sf(e);return $CLJS.Dc(d)?qp(d,b,e):new $CLJS.R(null,1,5,$CLJS.T,[new $CLJS.R(null,2,5,$CLJS.T,[$CLJS.gg.a(e),d],null)],null)},$CLJS.pc([a]))},rp=function(a){return $CLJS.Ac(a)?
a:$CLJS.Fc(a)?Wo(function(b){return $CLJS.gh.b($CLJS.Sd,qp(b,".",null))},a):$CLJS.gh.b($CLJS.Sd,qp(a,".",null))},tp=function(a){return $CLJS.Gd(Yo,$CLJS.Zc(function(b,c,d){return $CLJS.fh.b(b,sp($CLJS.Sd,Wo($CLJS.gg,$CLJS.Wh($CLJS.Sf(c),/\./)),d))},$CLJS.Ge,a))},vp=function(a){for(var b=$CLJS.F($CLJS.Co.a(a)),c=null,d=0,e=0;;)if(e<d){var f=c.O(null,e);$CLJS.q($CLJS.Bo.a(f))&&console.error("error:",$CLJS.Bo.a(f));e+=1}else if(b=$CLJS.F(b))c=b,$CLJS.Gc(c)?(b=$CLJS.Xd(c),e=$CLJS.Yd(c),c=b,d=$CLJS.ic(b),
b=e):(b=$CLJS.H(c),$CLJS.q($CLJS.Bo.a(b))&&console.error("error:",$CLJS.Bo.a(b)),b=$CLJS.K(c),c=null,d=0),e=0;else break;return console.error(up(a))},xp=function(a){return function(b){return function(c,d){d=$CLJS.Bh(d)?new $CLJS.Ka(null,2,[$CLJS.xo,d,$CLJS.so,vp],null):d;var e=null!=d&&(d.g&64||$CLJS.Gb===d.T)?$CLJS.Gd($CLJS.Ui,d):d,f=$CLJS.N.b(e,$CLJS.xo),g=$CLJS.N.b(e,$CLJS.so);return $CLJS.q($CLJS.Zb($CLJS.Do))?function(){var k=up($CLJS.kg.j(b,$CLJS.to,c,$CLJS.pc([$CLJS.Ao,a,$CLJS.zo,a]))),l=$CLJS.Zb($CLJS.Do);
return l.a?l.a(k):l(k)}().then(function(k,l,m,n){return function(p){var v=gp(p,$CLJS.pc([$CLJS.Sg,!0])),u=function(){var x=$CLJS.vo.a(v);return $CLJS.q(x)?x:$CLJS.Jg.a(v)}();if($CLJS.M.b(200,u)||$CLJS.Ya(u))return $CLJS.to.a(v);u=new $CLJS.Ka(null,1,[$CLJS.Co,new $CLJS.R(null,1,5,$CLJS.T,[new $CLJS.Ka(null,4,[$CLJS.Bo,"request failed",$CLJS.Jg,function(){var x=p.Od;return $CLJS.q(x)?x:p.status}(),$CLJS.uo,p.statusText,$CLJS.yo,p.data],null)],null)],null);return n.a?n.a(u):n(u)}}(d,e,f,g,b)).then(function(k,
l,m){return function(n){if($CLJS.q($CLJS.to.a(n)))return m.a?m.a(n):m(n);n=new $CLJS.Ka(null,1,[$CLJS.to,n],null);return m.a?m.a(n):m(n)}}(d,e,f,g,b)).catch(function(k,l,m,n){return function(p){p=new $CLJS.Ka(null,1,[$CLJS.Co,new $CLJS.R(null,1,5,$CLJS.T,[new $CLJS.Ka(null,2,[$CLJS.Bo,"request failed",$CLJS.wo,gp(p,$CLJS.pc([$CLJS.Sg,!1]))],null)],null)],null);return n.a?n.a(p):n(p)}}(d,e,f,g,b)):console.log("not init fetch fn")}}(wp.j($CLJS.pc([$CLJS.Eo,$CLJS.Sd])))},yp=function(a,b,c,d){if($CLJS.q($CLJS.q(c)?
d:c)){c=xp(c);var e=function(){return function(f){if($CLJS.q($CLJS.Zb($CLJS.nr))){var g=$CLJS.pc(["f-data:",$CLJS.to.a(f)]);$CLJS.og(g,$CLJS.Ra());$CLJS.Sa&&Vo($CLJS.Ra())}if($CLJS.q(b))return f=$CLJS.to.a(f),f=b.a?b.a(f):b(f),$CLJS.q(a)&&(a.a?a.a(f):a(f)),up(f);f=$CLJS.to.a(f);$CLJS.q(a)&&(a.a?a.a(f):a(f));return up($CLJS.H($CLJS.Nf(f)))}}(d,c);return c.b?c.b(d,e):c(d,e)}return console.log("should set endpoint url before query: ",d)},zp=function(a,b){if($CLJS.q($CLJS.M.b?$CLJS.M.b($CLJS.mo,b):$CLJS.M($CLJS.mo,
b))||$CLJS.q($CLJS.M.b?$CLJS.M.b($CLJS.oo,b):$CLJS.M($CLJS.oo,b)))$CLJS.xg.s($CLJS.ro,sp,new $CLJS.R(null,2,5,$CLJS.T,[a,$CLJS.Mo],null),!0);else throw Error(["No matching clause: ",$CLJS.z.a(b)].join(""));},Ap=function(a,b,c){var d=$CLJS.H(b);d=$CLJS.wh($CLJS.Sf(d),"by_props");var e=$CLJS.gg.a(function(){var l=$CLJS.Jo.a(c);return $CLJS.q(l)?l:a}()),f=$CLJS.Zb($CLJS.ro),g=d?$CLJS.lm(f,new $CLJS.R(null,2,5,$CLJS.T,[e,$CLJS.Fo],null)):$CLJS.lm(f,new $CLJS.R(null,2,5,$CLJS.T,[e,$CLJS.Ko],null)),k=d?
$CLJS.lm(f,new $CLJS.R(null,2,5,$CLJS.T,[e,$CLJS.Mo],null)):$CLJS.lm(f,new $CLJS.R(null,2,5,$CLJS.T,[e,$CLJS.Lo],null));return $CLJS.M.b(g,b)&&$CLJS.Ya(k)?d?$CLJS.lm(f,new $CLJS.R(null,2,5,$CLJS.T,[e,$CLJS.Io],null)):$CLJS.lm(f,new $CLJS.R(null,2,5,$CLJS.T,[e,$CLJS.oo],null)):null},Bp=function(a,b,c,d){$CLJS.M.b(c,$CLJS.no)?(a=$CLJS.lm($CLJS.Zb($CLJS.ro),new $CLJS.R(null,2,5,$CLJS.T,[a,b],null)),$CLJS.q(a)&&(d=up(tp(d)),a.a?a.a(d):a(d))):null!=c&&$CLJS.xg.s($CLJS.ro,sp,new $CLJS.R(null,2,5,$CLJS.T,
[a,b],null),c)},Dp=function(a,b){var c=$CLJS.lm($CLJS.Zb(a),new $CLJS.R(null,2,5,$CLJS.T,[b,$CLJS.Fo],null)),d=$CLJS.H(c);a=!$CLJS.Ac($CLJS.lm($CLJS.Zb(a),new $CLJS.R(null,2,5,$CLJS.T,[b,$CLJS.Io],null)));return $CLJS.q(a?c:a)?(zp(b,$CLJS.mo),yp($o(Cp,b,c),d,$CLJS.Zb($CLJS.qo),np(c))):null},Ep=function(a,b,c){$CLJS.Ac(b)?Dp($CLJS.ro,a):(b=$CLJS.im(b)?$CLJS.um($CLJS.he.b($CLJS.gg,b)):$CLJS.um(new $CLJS.R(null,1,5,$CLJS.T,[$CLJS.gg.a(b)],null)),Wo(function(d,e){return function(f){return Dp(e,f)}}(b,
$CLJS.ro),$CLJS.fh.b(b,a)),Wo(function(d,e){return function(f){var g=$CLJS.lm($CLJS.Zb(e),new $CLJS.R(null,2,5,$CLJS.T,[f,$CLJS.Ko],null)),k=$CLJS.H(g),l=!$CLJS.Ac($CLJS.lm($CLJS.Zb(e),new $CLJS.R(null,2,5,$CLJS.T,[f,$CLJS.oo],null)));$CLJS.q(l?g:l)?(zp(f,$CLJS.oo),f=yp($o(Cp,f,g),k,$CLJS.Zb($CLJS.qo),np(g))):f=null;return f}}(b,$CLJS.ro),b));return c},Fp=function(a,b,c){a=Ap(a,b,c);return new $CLJS.Ka(null,3,[$CLJS.Rg,np(b),$CLJS.Oo,a,$CLJS.No,b],null)},Gp=function(a,b,c,d,e){c=wp.j($CLJS.pc([c,
d]));d=$CLJS.Sf(b);a=0==d.lastIndexOf("delete_",0)?new $CLJS.R(null,2,5,$CLJS.T,[b,c],null):$CLJS.Ac(e)?new $CLJS.R(null,3,5,$CLJS.T,[b,c,new $CLJS.R(null,1,5,$CLJS.T,[$CLJS.po],null)],null):new $CLJS.R(null,3,5,$CLJS.T,[b,c,new $CLJS.R(null,1,5,$CLJS.T,[new $CLJS.R(null,2,5,$CLJS.T,[a,$CLJS.Lf(c)],null)],null)],null);a=Sp(new $CLJS.Ka(null,2,[$CLJS.Xn,new $CLJS.Ka(null,2,[$CLJS.xn,$CLJS.mn,$CLJS.Fn,d],null),$CLJS.Im,new $CLJS.R(null,1,5,$CLJS.T,[a],null)],null));return new $CLJS.Ka(null,2,[$CLJS.mn,
a,$CLJS.No,new $CLJS.R(null,2,5,$CLJS.T,[b,c],null)],null)},Tp=function(a,b,c,d){var e=$CLJS.H(b),f=function(){return function(g){var k=$CLJS.gg.a(function(){var m=$CLJS.Jo.a(d);return $CLJS.q(m)?m:a}()),l=$CLJS.Po.a(d);Cp.s(k,b,rp(g),l);return $CLJS.q(l)?(g=up(g),l.a?l.a(g):l(g)):null}}(e);$CLJS.q($CLJS.Zb($CLJS.nr))&&console.log("fetch:",c);return yp(f,e,$CLJS.Zb($CLJS.qo),c)},Ip=function(a,b,c,d,e){if($CLJS.Ac(d))return Tp(a,b,c,e);a=$CLJS.Po.a(e);d=up(d);$CLJS.q(a)&&(a.a?a.a(d):a(d));return new Promise(function(f,
g){return function(k){return k.a?k.a(g):k(g)}}(a,d))},Jp=function Jp(a){if(null!=a&&null!=a.Jc)return a.Jc(a);var c=Jp[$CLJS.Ca(null==a?null:a)];if(null!=c)return c.a?c.a(a):c(a);c=Jp._;if(null!=c)return c.a?c.a(a):c(a);throw $CLJS.ab("IEncodeJS.-clj-\x3ejs",a);},ep=function ep(a,b){if(null!=a&&null!=a.Hc)return a.Hc(a,b);var d=ep[$CLJS.Ca(null==a?null:a)];if(null!=d)return d.b?d.b(a,b):d(a,b);d=ep._;if(null!=d)return d.b?d.b(a,b):d(a,b);throw $CLJS.ab("IEncodeClojure.-js-\x3eclj",a);},fp=function fp(a){for(var c=
[],d=arguments.length,e=0;;)if(e<d)c.push(arguments[e]),e+=1;else break;return fp.j(0<c.length?new $CLJS.Nb(c.slice(0),0,null):null)};fp.j=function(a){a=a instanceof $CLJS.Nb&&0===a.m?a.c:Pp(a);return $CLJS.$e(a)};fp.A=0;fp.C=function(a){return this.j($CLJS.F(a))};
var sp=function sp(a,b,c){b=$CLJS.F(b);var e=$CLJS.H(b),f=$CLJS.K(b);return f?$CLJS.kg.f(a,e,function(){var g=$CLJS.N.b(a,e);return sp.f?sp.f(g,f,c):sp(g,f,c)}()):$CLJS.kg.f(a,e,c)},wp=function wp(a){for(var c=[],d=arguments.length,e=0;;)if(e<d)c.push(arguments[e]),e+=1;else break;return wp.j(0<c.length?new $CLJS.Nb(c.slice(0),0,null):null)};wp.j=function(a){return $CLJS.q($CLJS.Fh($CLJS.$c,a))?$CLJS.Wc(function(b,c){return $CLJS.fh.b($CLJS.q(b)?b:$CLJS.Sd,c)},a):null};wp.A=0;wp.C=function(a){return this.j($CLJS.F(a))};
var bp=function bp(a,b){return ap($CLJS.qm(bp,a),a,b)},up=function up(a){for(var c=[],d=arguments.length,e=0;;)if(e<d)c.push(arguments[e]),e+=1;else break;return up.j(arguments[0],1<c.length?new $CLJS.Nb(c.slice(1),0,null):null)};
up.j=function(a,b){var c=null!=b&&(b.g&64||$CLJS.Gb===b.T)?$CLJS.Gd($CLJS.Ui,b):b,d=$CLJS.N.f(c,$CLJS.Ng,$CLJS.Sf),e=function(){return function(g){var k=f;return(null!=g?$CLJS.Gb===g.Ic||(g.ic?0:$CLJS.Za(Qo,g)):$CLJS.Za(Qo,g))?Jp(g):"string"===typeof g||"number"===typeof g||g instanceof $CLJS.Q||g instanceof $CLJS.C?k.a?k.a(g):k(g):$CLJS.Yh($CLJS.pc([g]))}}(b,c,c,d),f=function(g,k,l,m){return function v(p){if(null==p)return null;if(null!=p?$CLJS.Gb===p.Ic||(p.ic?0:$CLJS.Za(Qo,p)):$CLJS.Za(Qo,p))return Jp(p);
if(p instanceof $CLJS.Q)return m.a?m.a(p):m(p);if(p instanceof $CLJS.C)return $CLJS.z.a(p);if($CLJS.Dc(p)){var u={};p=$CLJS.F(p);for(var x=null,D=0,I=0;;)if(I<D){var O=x.O(null,I),U=$CLJS.uc(O,0,null),Y=$CLJS.uc(O,1,null);O=u;U=e(U);Y=v(Y);O[U]=Y;I+=1}else if(p=$CLJS.F(p))$CLJS.Gc(p)?(D=$CLJS.Xd(p),p=$CLJS.Yd(p),x=D,D=$CLJS.ic(D)):(x=$CLJS.H(p),D=$CLJS.uc(x,0,null),I=$CLJS.uc(x,1,null),x=u,D=e(D),I=v(I),x[D]=I,p=$CLJS.K(p),x=null,D=0),I=0;else break;return u}if($CLJS.im(p)){u=[];p=$CLJS.F($CLJS.he.b(v,
p));x=null;for(I=D=0;;)if(I<D)O=x.O(null,I),u.push(O),I+=1;else if(p=$CLJS.F(p))x=p,$CLJS.Gc(x)?(p=$CLJS.Xd(x),I=$CLJS.Yd(x),x=p,D=$CLJS.ic(p),p=I):(p=$CLJS.H(x),u.push(p),p=$CLJS.K(x),x=null,D=0),I=0;else break;return u}return p}}(b,c,c,d);return f(a)};up.A=1;up.C=function(a){var b=$CLJS.H(a);a=$CLJS.K(a);return this.j(b,a)};var Yo=function Yo(a){for(var c=[],d=arguments.length,e=0;;)if(e<d)c.push(arguments[e]),e+=1;else break;return Yo.j(arguments[0],1<c.length?new $CLJS.Nb(c.slice(1),0,null):null)};
Yo.j=function(a,b){return $CLJS.q($CLJS.Fh($CLJS.$c,b))?$CLJS.Rc(function(c,d){return $CLJS.Dc(c)&&$CLJS.Dc(d)?Zo($CLJS.pc([c,d])):d},a,b):a};Yo.A=1;Yo.C=function(a){var b=$CLJS.H(a);a=$CLJS.K(a);return this.j(b,a)};var Cp=function Cp(a){switch(arguments.length){case 4:return Cp.s(arguments[0],arguments[1],arguments[2],arguments[3]);case 3:return Cp.f(arguments[0],arguments[1],arguments[2]);default:throw Error(["Invalid arity: ",$CLJS.z.a(arguments.length)].join(""));}};
Cp.s=function(a,b,c,d){if($CLJS.Fc(c))$CLJS.xg.s($CLJS.ro,sp,new $CLJS.R(null,2,5,$CLJS.T,[a,$CLJS.Io],null),c),$CLJS.xg.s($CLJS.ro,sp,new $CLJS.R(null,2,5,$CLJS.T,[a,$CLJS.Fo],null),b),$CLJS.xg.s($CLJS.ro,sp,new $CLJS.R(null,2,5,$CLJS.T,[a,$CLJS.Mo],null),!1),Bp(a,$CLJS.Go,d,c);else{var e=wp.j($CLJS.pc([$CLJS.lm($CLJS.Zb($CLJS.ro),new $CLJS.R(null,2,5,$CLJS.T,[a,$CLJS.oo],null)),c]));$CLJS.xg.s($CLJS.ro,sp,new $CLJS.R(null,2,5,$CLJS.T,[a,$CLJS.oo],null),e);$CLJS.xg.s($CLJS.ro,sp,new $CLJS.R(null,
2,5,$CLJS.T,[a,$CLJS.Ko],null),b);$CLJS.xg.s($CLJS.ro,sp,new $CLJS.R(null,2,5,$CLJS.T,[a,$CLJS.Lo],null),!1);Bp(a,$CLJS.Ho,d,c)}return c};Cp.f=function(a,b,c){return Cp.s(a,b,c,$CLJS.no)};Cp.A=4;var kI=new $CLJS.Q(null,"enable_log","enable_log",-1994769367);module.exports={set_endpoint_url:function(a){return pp(a)},hello:function(a){return["Hi devtools installed, ",$CLJS.z.a(a),"!"].join("")},init:function(a,b,c){$CLJS.q(b)&&$CLJS.$d($CLJS.Do,b);$CLJS.$d($CLJS.nr,kI.a(gp(c,$CLJS.pc([$CLJS.Sg,!0]))));return pp(a)},find_one:function(a,b,c,d){if($CLJS.q($CLJS.q(a)?b:a)){a=$CLJS.gg.a(a);b=gp(b,$CLJS.pc([$CLJS.Sg,!0]));c=Wo($CLJS.gg,c);d=gp(d,$CLJS.pc([$CLJS.Sg,!0]));if($CLJS.Ac(b))b=null;else{var e=$CLJS.H($CLJS.Lf(b));e=$CLJS.gg.a([$CLJS.Sf(a),"_by_",$CLJS.Sf(e)].join(""));
b=new $CLJS.R(null,3,5,$CLJS.T,[e,b,Wo(op,c)],null);b=Fp(a,b,d)}e=null!=b&&(b.g&64||$CLJS.Gb===b.T)?$CLJS.Gd($CLJS.Ui,b):b;b=$CLJS.N.b(e,$CLJS.Rg);c=$CLJS.N.b(e,$CLJS.Oo);e=$CLJS.N.b(e,$CLJS.No);return Ip(a,e,b,tp(c),d)}return null},find_many:function(a,b,c,d){if($CLJS.q(a)){a=$CLJS.gg.a(a);b=gp(b,$CLJS.pc([$CLJS.Sg,!0]));c=Wo($CLJS.gg,c);d=gp(d,$CLJS.pc([$CLJS.Sg,!0]));var e=$CLJS.gg.a([$CLJS.Sf(a),"_by_props"].join(""));c=Wo(op,c);b=$CLJS.Ac(b)?new $CLJS.R(null,2,5,$CLJS.T,[e,c],null):new $CLJS.R(null,
3,5,$CLJS.T,[e,b,c],null);b=Fp(a,b,d);e=null!=b&&(b.g&64||$CLJS.Gb===b.T)?$CLJS.Gd($CLJS.Ui,b):b;b=$CLJS.N.b(e,$CLJS.Rg);c=$CLJS.N.b(e,$CLJS.Oo);e=$CLJS.N.b(e,$CLJS.No);a=Ip(a,e,b,Wo(tp,c),d)}else a=null;return a},insert:function(a,b,c,d){if($CLJS.q($CLJS.q(a)?b:a)){a=$CLJS.gg.a(a);b=gp(b,$CLJS.pc([$CLJS.Sg,!0]));c=$CLJS.q(c)?Wo($CLJS.gg,c):null;d=gp(d,$CLJS.pc([$CLJS.Sg,!0]));var e=$CLJS.gg.a(["create_",$CLJS.Sf(a)].join(""));b=Gp(a,e,b,null,c);b=null!=b&&(b.g&64||$CLJS.Gb===b.T)?$CLJS.Gd($CLJS.Ui,
b):b;b=$CLJS.N.b(b,$CLJS.mn);a=yp($o(Ep,a,$CLJS.Jo.a(d)),null,$CLJS.Zb($CLJS.qo),b)}else a=null;return a},update:function(a,b,c,d,e){if($CLJS.q($CLJS.q(a)?b:a)){a=$CLJS.gg.a(a);b=gp(b,$CLJS.pc([$CLJS.Sg,!0]));c=gp(c,$CLJS.pc([$CLJS.Sg,!0]));d=$CLJS.q(d)?Wo($CLJS.gg,d):null;e=gp(e,$CLJS.pc([$CLJS.Sg,!0]));var f=$CLJS.gg.a(["update_",$CLJS.Sf(a)].join(""));b=Gp(a,f,b,c,d);b=null!=b&&(b.g&64||$CLJS.Gb===b.T)?$CLJS.Gd($CLJS.Ui,b):b;b=$CLJS.N.b(b,$CLJS.mn);a=yp($o(Ep,a,$CLJS.Jo.a(e)),null,$CLJS.Zb($CLJS.qo),
b)}else a=null;return a},remove:function(a,b,c){if($CLJS.q($CLJS.q(a)?b:a)){a=$CLJS.gg.a(a);b=gp(b,$CLJS.pc([$CLJS.Sg,!0]));c=gp(c,$CLJS.pc([$CLJS.Sg,!0]));var d=$CLJS.gg.a(["delete_",$CLJS.Sf(a)].join(""));b=Gp(a,d,b,null,null);b=null!=b&&(b.g&64||$CLJS.Gb===b.T)?$CLJS.Gd($CLJS.Ui,b):b;b=$CLJS.N.b(b,$CLJS.mn);a=yp($o(Ep,a,$CLJS.Jo.a(c)),null,$CLJS.Zb($CLJS.qo),b)}else a=null;return a}};